### PR TITLE
[WIP] Units convert_value PR-1

### PR DESCRIPTION
**Pull request by carldlaird**
Implemented the convert_value method to convert numerical values using Pyomo units objects.

## Summary/Motivation:
- need a convert value method for working with constants containing Pyomo units.

## Changes proposed in this PR:
- implemented the convert_value method on the PyomoUnitsContainer to allow
for conversion of numerical values based on Pyomo Units.
- Changed the singleton behavior to access the singleton units container through a module function.

### Legal Acknowledgement

By contributing to this software project, I agree to the following terms and conditions for my contribution:

1. I agree my contributions are submitted under the BSD license.
2. I represent I am authorized to make the contributions and grant the license. If my employer has rights to intellectual property that includes these contributions, I represent that I have received permission to make contributions and grant the required license on behalf of that employer.

### CODE REVIEW

**Comment by jsiirola** [comment]
Note also that the documentation builds are failing due to the API change from `pyo.units` to `pyo.units()`.

**Comment by carldlaird** [comment]
@jsiirola Addressing your comment above where you provide sample code that would allow us to keep the module.units instead of module.units(). I don't think the complexity of that shell class is worth it just to prevent someone from accessing the singleton through a module function instead of a module property. It seems like the solution implemented (model.units()) is really straightforward to see what is happening.

@jsiirola Addressing your comment above about going to the full convert - it is not quite as simple as you illustrate, but it is close. I have the code and will work on making the change tomorrow (there needs to be some checking for offset units). I propose then, that we have two methods:
- convert takes in a Pyomo expression (hopefully with units) as well as "to_units" and returns the expression that does the conversion (close to your code above).
- convert_value takes in a numerical value or Pyomo expression, and must have a from_units and a to_units and just does the numerical conversion.

Maybe most people would just use "pyo.value(u.convert(expr, to_units=u.kg/u.s))" instead of convert_value?

**Comment by carldlaird** [comment]
Thinking about it more, maybe there is no need for the convert_value method since wrapping the result with pyo.value basically does this anyway.

**Comment by jsiirola** [comment]
I think the thing that bothers me about `pyo.units()` stems from the old guidance to make methods verbs (or verb phrases). It is not clear to me what action `units()` is doing without consulting the documentation.  

The simplicity of a module property was nice and by design, the wrapper class requires no maintenance (it will “automatically track” any future changes to the PyomoUnitsContainer API.

**Comment by michaelbynum** [comment]
@jsiirola I am not convinced that your suggestion does not require maintenance. The code you suggested may cause future developers confusion. I also don't see a problem with having a function as long as the examples and documentation are clear.

**Comment by michaelbynum** [comment]
Another simple options would be to not import units with pyomo.environ. If someone wants to import units, they can import it explicitly, and an ImportError would be raised if pint is not available.

**Comment by carldlaird** [comment]
@michaelbynum That's not a bad idea. I have to look and see if the imports will be required in variables or parameters to support the next step. I will get back to you as soon as I can.

**Comment by jsiirola** [comment]
Not pulling it into `pyomo.environ` would force users to start off with `from pyomo.core.base.units_container import units`, correct?

FWIW, the mock (duck-typed) interface it is a paradigm that we already use in one form or another in several places in Pyomo (Abstract classes in the Set rewrite, pyqt in `contrib.viewer`, and resolving Py2/Py3 API changes that are not handled by `six` are three that come to mind).

I went back and looked at the use of the `units` singleton, and I am 99% certain we can get away with a much simpler class:
```python
class PyomoUnitsContainer_noPint(object):
    def __getattr__(self, attr):
         raise RuntimeError(
            "The default `units` singleton is not available because the "
            "required Python package 'pint' could not be imported."
            " Please make sure you have 'pint' installed.")

if pint_module is not None:
    units = PyomoUnitsContainer()
else:
    units = PyomoUnitsContainer_noPint()
```

**Comment by michaelbynum** [comment]
Is there something wrong with requiring `from Pyomo.core.base.units_container import units`?

**Comment by michaelbynum** [comment]
@jsiirola I do like this simpler class much better.

**Comment by jsiirola** [comment]
@michaelbynum: Only that it would be the first "significant" piece of functionality that a normal user might run across that would require a direct import from inside of `base`.

**Comment by carldlaird** [comment]
What if we put the import at pyomo.units? Then units would look like other packages and this would also have the benefit that these imports were not executed if units is not used.

If you think this is a good idea, what is the best way to implement? Put a units folder at the main level with a __init__? If so, we could also move the code here.

Thoughts?

**Pull request closed without merging**
