### PR TITLE
Rewrite Test Driver Script

### PR DESCRIPTION
**Pull request by mrmundt**
## Summary/Motivation:
The old test driver script `pyomo.scripting.runtests` was based on PyUtilib's `dev.runtests`. This replaces that with a modernized, condensed version and removes the `test.pyomo` console scripts.

## Changes proposed in this PR:
- Remove `pyomo.scripting.runtests`
- Add new test driver to `pyomo.common.unittest`
- Change Jenkins and GitHub Action drivers to use `python -m pyomo.common.unittest`

### Legal Acknowledgement

By contributing to this software project, I have read the [contribution guide](https://pyomo.readthedocs.io/en/stable/contribution_guide.html) and agree to the following terms and conditions for my contribution:

1. I agree my contributions are submitted under the BSD license.
2. I represent I am authorized to make the contributions and grant the license. If my employer has rights to intellectual property that includes these contributions, I represent that I have received permission to make contributions and grant the required license on behalf of that employer.

### CODE REVIEW

**Review by blnicho — COMMENTED** [review]
There are still a few references to `pyutilib.th` in `pyomo/common/unittest.py`, can these be removed? I guess I'm not quite following the "big picture" sequence of steps required for this transition between this PR, #1859, and/or any subsequent PRs.

**Comment by mrmundt** [comment]
> There are still a few references to `pyutilib.th` in `pyomo/common/unittest.py`, can these be removed? I guess I'm not quite following the "big picture" sequence of steps required for this transition between this PR, #1859, and/or any subsequent PRs.

Because we haven't merged #1859 yet, I didn't want to include those changes in this PR. These changes are also independent of each other (as in, one replaces `pyutilib.th` and one replaces `pyutilib.dev.runtests`).

I did test these changes against the `py-unittest` branch, so I'm confident that they will appropriately mix. They just didn't make sense to put in a single PR because they touch different parts of the testing suite.

**Comment by blnicho** [comment]
> 
> Because we haven't merged #1859 yet, I didn't want to include those changes in this PR. These changes are also independent of each other (as in, one replaces `pyutilib.th` and one replaces `pyutilib.dev.runtests`).
> 
> I did test these changes against the `py-unittest` branch, so I'm confident that they will appropriately mix. They just didn't make sense to put in a single PR because they touch different parts of the testing suite.

Got it, thanks for the clarification!

**Comment by jsiirola** [comment]
@mrmundt Any idea why the coverage went down?  It looks like some pynumero and parmest code is no longer being tested?

**Comment by jsiirola** [comment]
The weird thing is that it is consistent: both builds for this PR have the same coverage...

**Comment by jsiirola** [comment]
Interesting.  The problem appears to be the test's use of `pyomo.common.fileutils.import_file`.  If I change the test as follows:
```diff
diff --git a/pyomo/contrib/pynumero/tests/test_cyipopt_examples.py b/pyomo/contrib/pynumero/tests/test_cyipopt_examples.py
index 258699e..0957ddc 100644
--- a/pyomo/contrib/pynumero/tests/test_cyipopt_examples.py
+++ b/pyomo/contrib/pynumero/tests/test_cyipopt_examples.py
@@ -135,14 +135,14 @@ class TestExamples(unittest.TestCase):
         baseline = pandas.read_csv(data_fname)
 
         # test the data generator
-        ex = import_file(os.path.join(example_dir, 'external_grey_box', 'param_est', 'generate_data.py'))
+        import pyomo.contrib.pynumero.examples.external_grey_box.param_est.generate_data as ex
         df1 = ex.generate_data(5, 200, 5, 42)
         df2 = ex.generate_data_external(5, 200, 5, 42)
         pandas.testing.assert_frame_equal(df1, baseline, atol=1e-3)
         pandas.testing.assert_frame_equal(df2, baseline, atol=1e-3)
 
         # test the estimation
-        ex = import_file(os.path.join(example_dir, 'external_grey_box', 'param_est', 'perform_estimation.py'))
+        import pyomo.contrib.pynumero.examples.external_grey_box.param_est.perform_estimation as ex
 
         m = ex.perform_estimation_external(data_fname, solver_trace=False)
         self.assertAlmostEqual(pyo.value(m.UA), 204.43761, places=3)
```
Then coverage finds the file and reports coverage.  My guess is that because `import_file` ignores the fact that we are importing something that happens to actually be in a valid module the coverage is getting reported as if, e.g., `generate_data` was a top-level module and not in `pyomo.common.pynumero.examples.external_grey_box.param_est`

**Review by jsiirola — APPROVED** [review]

**Review by blnicho — APPROVED** [review]

**Comment by mrmundt** [comment]
@jsiirola - This is actually good for review now.

**Comment by mrmundt** [comment]
Some changes made here should be reevaluated as part of #1885

**Review by jsiirola — APPROVED** [review]

**Pull request merged**
