### PR TITLE
Fix GAMS writer replace_power to support function-wrapped powers

### LINKED ISSUE #244: GAMS writer fails for power nested in a log
The functionality to selectively replace `**` with `power()` fails in an edge case when `**` is nested within a `log` function, e.g. `log(x ** 2)`. In `replace_power()`, the `assert` that `arg` is bound by `(` and `)` fails because the arg is bound by `log(` and `)`. This is possibly also true with other similar functions, e.g. `exp()`.

@gseastream

### PR DESCRIPTION
**Pull request by gseastream**
Fixes #244

### CODE REVIEW

**Comment by qtothec** [comment]
May want to add a quick test in there for this case.

**Comment by whart222** [comment]
I'm closing this pull request after confirming that the changes in the expr_dev branch account for the error considered here.

**Comment by whart222** [comment]
John wanted this PR re-opened to support an upcoming release on the master branch.

**Comment by jsiirola** [comment]
(Spoke with @carldlaird and he was also OK merging this PR.  Going ahead and merging it)

**Pull request merged**
