### PR TITLE
GAMS: handle fixed variables in LinearExpressions

### LINKED ISSUE #924: GAMS writer fails to identify fixed variables in LinearExpression
The following two tests both fail because the GAMS writer is not able to properly handle the fixed variables in `LinearExpression`.

```
    def test_quicksum(self):
        m = ConcreteModel()
        m.y = Var(domain=Binary)
        m.c = Constraint(expr=quicksum([m.y, m.y], linear=True) == 1)
        m.y.fix(1)
        lbl = NumericLabeler('x')
        smap = SymbolMap(lbl)
        tc = StorageTreeChecker(m)
        self.assertEqual(expression_to_string(m.c.body, tc, smap=smap), "2")
```
expected: `1 + 1`; output: `x1 + x1`

```
    def test_quicksum_integer_var_fixed(self):
        m = ConcreteModel()
        m.x = Var()
        m.y = Var(domain=Binary)
        m.c = Constraint(expr=quicksum([m.y, m.y], linear=True) == 1)
        m.o = Objective(expr=m.x ** 2)
        m.y.fix(1)
        os = StringIO()
        m.write(os, format='gams')
        self.assertIn("USING nlp", os.getvalue())
```

I suspect that this is related in some way to #919, but I am still working to understand the GAMS visitor enough again.

@gseastream Any quick thoughts?

### PR DESCRIPTION
**Pull request by jsiirola**
## Summary/Motivation:
Alternative implementation to #917: fixes the bug where fixed variables appearing in a Linear Expression are sent to GAMS as free variables.

This implementation adds extra processing to make sure that any fixed variables that are emitted by the expression walkers (e.g., in the case of LinearExpression) are marked as 'fixed' in the GAMS input.  An alternative implementation (#917) adds special processing for the LinearExpression node in the `ToGamsVisitor`.

The advantage of this implementation is that it should also correctly handle other (future) cases where a fixed variable could sneak through the visitor logic.  The advantage of the #917 implementation is that fixed variables are completely hidden from GAMS.

## Changes proposed in this PR:
- catch fixed variables in the variable categorization logic and output them to GAMS as fixed.
- add a test to the writer for this situation (with LinearExpression nodes)

### Legal Acknowledgement

By contributing to this software project, I have read the [contribution guide](https://pyomo.readthedocs.io/en/stable/contribution_guide.html) and agree to the following terms and conditions for my contribution:

1. I agree my contributions are submitted under the BSD license.
2. I represent I am authorized to make the contributions and grant the license. If my employer has rights to intellectual property that includes these contributions, I represent that I have received permission to make contributions and grant the required license on behalf of that employer.

### CODE REVIEW

**Comment by jsiirola** [comment]
@qtothec: we should pick one of these fixes (#917 or #1463) for fixed variables in GAMS.  What are your thoughts?

**Comment by qtothec** [comment]
I forgot to mention: the added commit is just porting the tests over from the other PR.

**Comment by jsiirola** [comment]
@qtothec, do you think we need the same sort of fix for the Baron writer?

**Comment by qtothec** [comment]
@jsiirola Yes, it at least looks like the result you get back can be incorrect:
```
Model unknown

  Variables:
    y : Size=1, Index=None
        Key  : Lower : Value : Upper : Fixed : Stale : Domain
        None :     0 :     0 :     1 :  True :  True : Binary
    x : Size=1, Index=None
        Key  : Lower : Value : Upper : Fixed : Stale : Domain
        None :     0 :   0.0 :  None : False : False :  Reals

  Objectives:
    obj : Size=1, Index=None, Active=True
        Key  : Active : Value
        None :   True :   0.0

  Constraints:
    c1 : Size=1
        Key  : Lower : Body : Upper
        None :   0.0 :    0 :  None
    c2 : Size=1
        Key  : Lower : Body : Upper
        None :   1.0 :  0.0 :   1.0
```

Note `c2` on the test problem you added.

**Pull request merged**
