### PR TITLE
_component_data_iter now uses sorted_robust

### LINKED ISSUE #1845: `_component_data_iter` I think doesn't use `sorted_robust`?
This is still related to #567, but now I'm confused. On master (after #1842), now the `pprint` statement in the following code works, but the writer still throws the `TypeError` because it cannot sort the tuples in `m.ick`:
```
from pyomo.environ import *

m = ConcreteModel()
m.ick = Set(initialize=[(1, 'str1'), ('str2', 'str3')], ordered=True,
            within=Any)
m.v = Var(m.ick, within=Binary)
m.obj = Objective(expr=m.v[1, 'str1'])
m.cons = Constraint(expr=m.v[1,'str1'] >= m.v['str2', 'str3'])

m.pprint() # this is okay
SolverFactory('gurobi').solve(m, tee=True) # this throws the error below
```
```
Traceback (most recent call last):
  File "sorting_stuff.py", line 11, in <module>
    SolverFactory('gurobi').solve(m, tee=True)
  File "/home/esjohn/src/pyomo/pyomo/opt/base/solvers.py", line 574, in solve
    self._presolve(*args, **kwds)
  File "/home/esjohn/src/pyomo/pyomo/solvers/plugins/solvers/GUROBI.py", line 230, in _presolve
    ILMLicensedSystemCallSolver._presolve(self, *args, **kwds)
  File "/home/esjohn/src/pyomo/pyomo/opt/solver/shellcmd.py", line 200, in _presolve
    OptSolver._presolve(self, *args, **kwds)
  File "/home/esjohn/src/pyomo/pyomo/opt/base/solvers.py", line 674, in _presolve
    **kwds)
  File "/home/esjohn/src/pyomo/pyomo/opt/base/solvers.py", line 740, in _convert_problem
    **kwds)
  File "/home/esjohn/src/pyomo/pyomo/opt/base/convert.py", line 100, in convert_problem
    problem_files, symbol_map = converter.apply(*tmp, **tmpkw)
  File "/home/esjohn/src/pyomo/pyomo/solvers/plugins/converter/model.py", line 82, in apply
    io_options=io_options)
  File "/home/esjohn/src/pyomo/pyomo/core/base/block.py", line 1812, in write
    io_options)
  File "/home/esjohn/src/pyomo/pyomo/repn/plugins/cpxlp.py", line 172, in __call__
    include_all_variable_bounds=include_all_variable_bounds)
  File "/home/esjohn/src/pyomo/pyomo/repn/plugins/cpxlp.py", line 451, in _print_model_LP
    Var, sort=sortOrder) )
  File "/home/esjohn/src/pyomo/pyomo/core/base/block.py", line 1435, in component_data_objects
    sort=sort):
  File "/home/esjohn/src/pyomo/pyomo/core/base/block.py", line 1361, in _component_data_iter
    _items = sorted(_items, key=itemgetter(0))
TypeError: '<' not supported between instances of 'str' and 'int'
```
Should `_component_data_iter` be using `sorted_robust`?

### PR DESCRIPTION
**Pull request by PierreAttard**
## Fixes # .
Fix #1845
## Summary/Motivation:
This resolves an issue with sorted_robust reported by @emma58 in #1845. 
Block._component_data_iter  does not use the correction did @jsiirola in the PR #1842. I just add his correction to the current PR in order to solve #1845.

## Changes proposed in this PR:
- Extend the `sorted_robust` API to accept `key=` and `reverse=` arguments
- import `sorted_robust` in block.py and sort with  `sorted_robust` ~~instead of `six.itemgetter`~~

### Legal Acknowledgement

By contributing to this software project, I have read the [contribution guide](https://pyomo.readthedocs.io/en/stable/contribution_guide.html) and agree to the following terms and conditions for my contribution:

1. I agree my contributions are submitted under the BSD license.
2. I represent I am authorized to make the contributions and grant the license. If my employer has rights to intellectual property that includes these contributions, I represent that I have received permission to make contributions and grant the required license on behalf of that employer.

### CODE REVIEW

**Comment by jsiirola** [comment]
We definitely need to move to using `sorted_robust`, but we need to preserve the use of `itemgetter(0)` so that component data objects are not accidentally compared.  There is a PR to this PR (PierreAttard/pyomo#1) that extends the `sorted_robust` API to support `key=` and `reverse=` arguments and adds tests.  If/once merged, then this PR should be ready to go.

**Review by jsiirola — APPROVED** [review]
Looks good, pending successful tests

**Comment by PierreAttard** [comment]
Is that possible to re-run a specific test ?

Win3.6 and 3.8 tests fails because of that : 

image

**Comment by jsiirola** [comment]
Unfortunately, no.  GHA only supports "rerun everything".  We will wait to see if everything else passes, and if it does, I would be comfortable merging even with those failures (as they are unrelated to this PR).

**Review by blnicho — APPROVED** [review]

**Pull request merged**
