### PR TITLE
Conditionally choose lp or mip solver based on problem for XPRESS

### PR DESCRIPTION
**Pull request by kdheepak**
This addresses #58

### CODE REVIEW

**Comment by ghackebeil** [comment]
I don't think this will fix this problem. The main problem file always ends with .lp (unless you are using the xpress_ampl interface). Have you tested this?

**Comment by kdheepak** [comment]
You are right. I was using `solver_io='mps'` in the example that I tested
with, and it worked then. What is the way to find if the problem is a mip
in the solver instance?

**Comment by kdheepak** [comment]
I've updated the pull request. This will allow the user to pass `is_mip=True` as a keyword argument when creating a solver instance to call `mipoptimize` during a solve. There may be better ways to achieve the same effect. This PR can be considered a temporary fix, while a better implementation can be discussed. This offers the choice to the user while also being backward compatible.

**Comment by ghackebeil** [comment]
I think this is a good short term fix as well. I won't have time to look at the longer term fix for a least a week or two, but it will involve the problem writers (LP, MPS, NL) returning a classification of the model in some form (LP, MIP, QP, QCP, MIQCP, etc.), which I think could be useful in other contexts.

**Pull request merged**
