### PR TITLE
CBC plugin patch

### PR DESCRIPTION
**Pull request by michaelbynum**
## Summary/Motivation:
This PR fixes the signs of the objective, duals, and reduced costs for maximization problems with CBC.

### Legal Acknowledgement

By contributing to this software project, I have read the [contribution guide](https://pyomo.readthedocs.io/en/stable/contribution_guide.html) and agree to the following terms and conditions for my contribution:

1. I agree my contributions are submitted under the BSD license.
2. I represent I am authorized to make the contributions and grant the license. If my employer has rights to intellectual property that includes these contributions, I represent that I have received permission to make contributions and grant the required license on behalf of that employer.

### CODE REVIEW

**Comment by ghackebeil** [comment]
I think there is a CBC expected failure in `pyomo/solvers/tests/testcases.py` that you can remove with this as well.

**Comment by michaelbynum** [comment]
Good catch @ghackebeil. I'll take care of that.

**Review by jsiirola — DISMISSED** [review]

**Comment by michaelbynum** [comment]
Yeah, I should be able to fix the failing tests this afternoon.

**Comment by michaelbynum** [comment]
It is not clear to me what the test in test_fix_parsing_bug (pyomo.solvers.tests.checks.test_CBCplugin.TestCBCUsingMock) is doing. I would appreciate it if someone else had a look at my changes to this test.

**Review by blnicho — APPROVED** [review]

**Pull request merged**
