### PR TITLE
Minor FBBT Fixes and Tests

### PR DESCRIPTION
**Pull request by michaelbynum**
## Changes proposed in this PR:
- Fixes a bug in the iteration limit for FBBT.
- Ensures `compute_bounds_on_expr` returns None instead of `inf`
- Adds tests for the above changes
- Fixed the BigM _estimate_M method to account for changes to FBBT
- Added quadratic=False to the call to generate_standard_repn in _estimate_M to ensure quadratic constraints are handled properly in the BigM transformation

### Legal Acknowledgement

By contributing to this software project, I agree to the following terms and conditions for my contribution:

1. I agree my contributions are submitted under the BSD license.
2. I represent I am authorized to make the contributions and grant the license. If my employer has rights to intellectual property that includes these contributions, I represent that I have received permission to make contributions and grant the required license on behalf of that employer.

### CODE REVIEW

**Comment by qtothec** [comment]
Wait, `compute_bounds_on_expr` is suddenly going to start returning `(None, None)` instead of `(-inf, inf)`?

**Comment by qtothec** [comment]
Because I just told XY that he can use `compute_bounds_on_expr` for `MatOpt` a couple days ago, and at that point the expected output was `(-inf, inf)`.

**Comment by michaelbynum** [comment]
@qtothec I made this change to be consistent with the return values of `fbbt`. Can you explain how this is problematic for MatOpt?

**Comment by michaelbynum** [comment]
And to be consistent with variable bounds, which use `None` to indicate infinite.

**Comment by qtothec** [comment]
@michaelbynum No strong opinions on whether it should be one way or another. Just wanted more of a warning that an API change was happening.

**Pull request merged**
