### PR TITLE
[WIP] Initial implementation of excel interface

### PR DESCRIPTION
**Pull request by gseastream**
Read and write pyomo model data to excel file.

I put this file in pyomo.core.plugins.data, is this the right place for it? Also, is there a factory that creates the classes located in this directory? If so, what factory is that and how can I register my writer and/or reader with it?

### CODE REVIEW

**Comment by qtothec** [comment]
@whart222 @jsiirola Anything feedback on file location or the Factory questions that @gseastream has?

**Comment by gseastream** [comment]
@ghackebeil @jsiirola I'm making good progress on the excel writer, but I'm still wondering about the file placement I chose above. Is pyomo.core.plugins.data the right place for the excel writer? And would it be the right place for the excel reader that loads values back into pyomo? Lastly, is there a Factory of some sort that can create a writer class for files in this directory? Thanks!

**Comment by jsiirola** [comment]
@gseastream: The location isn't super-critical.  For lack of a better place, I would start with `pyomo/repn/plugins`; the logic being that this is a form of model "writer".  Following that logic, I am thinking it should hook into the `AbstractProblemWriter`.  While this is not a "solver interface", so things like the `solver_capabilities` flag is a bit weird, it is a method to write a model out to a particular format.  Plus, it seems to make sense to me that a user would like to:

```
model.write('foo.xls')
```

(Of course, to implement that, you will have to add `xls` to `pyomo/opt/base/formats` ... although we should extend the `IProblemWriter` interface so that the `guess_format` function would work by querying the extension point instead of the hard-coded list.) 

@whart222: Any thoughts?

**Comment by gseastream** [comment]
Commenting since this may be worth noting, but since this writer uses pandas and imports it in the file, the user is required to have pandas installed to run:
```python
from pyomo.environ import *
```
While this is not the only pyomo utility that uses pandas, this appears to be the first one included in `pyomo.environ` that uses it. I found this out because I got an error when trying to do the above import with an installation that did not have pandas. This only arose now because I just moved it to `repn/plugins`.

**Comment by qtothec** [comment]
You could wrap the import in a try/except with a `pandas_available` flag and raise an exception if they try to use this writer with extinct `pandas`.

**Comment by qtothec** [comment]
@gseastream It appears that there might be a bug causing `IndexError` for empty components. For example, I can have an `IndexedConstraint` that has zero elements due to use of `Constraint.Skip`:
```
@m.Constraint(m.a_set)
def empty_constraint(m, set_elem):
    return Constraint.Skip
```

Traceback:
```
IndexError                                Traceback (most recent call last)
<ipython-input-5-b2d2962f7699> in <module>()
      1 m.fuel_reactor = FuelRxnCocur(parent=m)
      2 m.display()
----> 3 m.write('model.xlsx')
      4 m.obj = Objective(expr=-1 * m.fuel_reactor.gas_out.F_unit)

/home/qichen/.solvers/pyomo/src/pyomo/pyomo/core/base/block.py in write(self, filename, format, solver_capability, io_options)
   1645                                           filename,
   1646                                           solver_capability,
-> 1647                                           io_options)
   1648         smap_id = id(smap)
   1649         if not hasattr(self, 'solutions'):

/home/qichen/.solvers/pyomo/src/pyomo/pyomo/repn/plugins/excel_writer.py in __call__(self, model, output_filename, solver_capability, io_options)
     72         filename = self.write_excel(all_frames,
     73                                     filename=output_filename,
---> 74                                     engine=engine)
     75         return filename, None
     76 

/home/qichen/.solvers/pyomo/src/pyomo/pyomo/repn/plugins/excel_writer.py in write_excel(self, all_frames, filename, engine)
    333                           writer=writer,
    334                           objectMap=objectMap,
--> 335                           sheet_namer=sheet_namer)
    336 
    337         names = []

/home/qichen/.solvers/pyomo/src/pyomo/pyomo/repn/plugins/excel_writer.py in _write_excel(self, all_frames, writer, objectMap, sheet_namer, parent, parent_row)
    526                 self._write_excel(item, writer=writer, parent_row=toc_row,
    527                                   parent=toc_name, objectMap=objectMap,
--> 528                                   sheet_namer=sheet_namer)
    529                 # This is the only case where the extra info at
    530                 # the top of the sheet is not needed.

/home/qichen/.solvers/pyomo/src/pyomo/pyomo/repn/plugins/excel_writer.py in _write_excel(self, all_frames, writer, objectMap, sheet_namer, parent, parent_row)
    586                 df.to_excel(writer, sheet_name=obj_sheet_name, startrow=2,
    587                             merge_cells=False,
--> 588                             freeze_panes=(3, 0))
    589 
    590             cols = df.index.nlevels + len(df.columns)

/home/qichen/.solvers/pyomo/local/lib/python2.7/site-packages/pandas/core/frame.pyc in to_excel(self, excel_writer, sheet_name, na_rep, float_format, columns, header, index, index_label, startrow, startcol, engine, merge_cells, encoding, inf_rep, verbose, freeze_panes)
   1422         formatter.write(excel_writer, sheet_name=sheet_name, startrow=startrow,
   1423                         startcol=startcol, freeze_panes=freeze_panes,
-> 1424                         engine=engine)
   1425 
   1426     def to_stata(self, fname, convert_dates=None, write_index=True,

/home/qichen/.solvers/pyomo/local/lib/python2.7/site-packages/pandas/io/formats/excel.pyc in write(self, writer, sheet_name, startrow, startcol, freeze_panes, engine)
    626         writer.write_cells(formatted_cells, sheet_name,
    627                            startrow=startrow, startcol=startcol,
--> 628                            freeze_panes=freeze_panes)
    629         if need_save:
    630             writer.save()

/home/qichen/.solvers/pyomo/local/lib/python2.7/site-packages/pandas/io/excel.pyc in write_cells(self, cells, sheet_name, startrow, startcol, freeze_panes)
   1567             wks.freeze_panes(*(freeze_panes))
   1568 
-> 1569         for cell in cells:
   1570             val = _conv_value(cell.val)
   1571 

/home/qichen/.solvers/pyomo/local/lib/python2.7/site-packages/pandas/io/formats/excel.pyc in get_formatted_cells(self)
    594     def get_formatted_cells(self):
    595         for cell in itertools.chain(self._format_header(),
--> 596                                     self._format_body()):
    597             cell.val = self._format_value(cell.val)
    598             yield cell

/home/qichen/.solvers/pyomo/local/lib/python2.7/site-packages/pandas/io/formats/excel.pyc in _format_header_regular(self)
    430                 coloffset = 1
    431                 if isinstance(self.df.index, MultiIndex):
--> 432                     coloffset = len(self.df.index[0])
    433 
    434             colnames = self.columns

/home/qichen/.solvers/pyomo/local/lib/python2.7/site-packages/pandas/core/indexes/multi.pyc in __getitem__(self, key)
   1375             retval = []
   1376             for lev, lab in zip(self.levels, self.labels):
-> 1377                 if lab[key] == -1:
   1378                     retval.append(np.nan)
   1379                 else:

IndexError: index 0 is out of bounds for axis 0 with size 0
```

**Comment by qtothec** [comment]
Yeah, there hasn't been documentation or tests developed for this yet. The hand-waving documentation is that it replicates the GAMS 'export all symbols to Excel' functionality (variables, constraints, sets, etc.), but extended to accommodate hierarchical model structure (due to nested Blocks/Disjuncts).

The reason that this is hooked onto the problem writer infrastructure is because there wasn't a good alternative.

**Comment by gseastream** [comment]
Since I don't see myself (or anyone else) working on this anytime soon, nor does there seem to be any demand for it, I'm gonna close this until further notice to clean up the list of pull requests. The conversation above will remained archived here if this project is ever picked back up.

**Pull request closed without merging**
