### PR TITLE
PyNumero

### PR DESCRIPTION
**Pull request by santiagoropb**
## Summary/Motivation:
This PR contains a collection of tools for writing optimization algorithms from python using pyomo, numpy and scipy as the core development packages. The package is divided into three main subpackages and a collection of examples. Those are:

- pyomo.contrib.pynumero.interfaces
- pyomo.contrib.pynumero.sparse
- pyomo.contrib.pynumero.linalg
- pyomo.contrib.pynumero.examples

The first subpackage contains functionality for building nonlinear programming problems from pyomo models. The PyomoNLP object is basically an interface between pyomo concrete and abstract models to a numpy/scipy based class for evaluating NLP functions. These include evaluation of objective and constraints as well as jacobians and hessians of Lagrangian functions. 

The second subpackage has functionality for block-linear-algebra storage. This is very similar functionality to what the package BlockTools offered. However, pynumero.sparse is based on numpy/scipy for manipulating block-vectors and block-matrices from python. In addition, pynumero.sparse contains implementations for parallel block-vectors and matrices. This is done via MPI4py

The third subpackage contains interfaces to linear solvers. The current PR considers direct linear solvers for symmetric indefinite systems. However, the intention is to get more solver in pynumero.linalg included in future releases of pynumero. Currently, we offer interfaces to MA27, MA57 and MUMPS 5.1. Although these linear solvers are in C and Fortran, we provide python interfaces using ctypes and precompiled code.

The fourth subdirectory contains examples for users to get familiar with the tools and functionality offered in pynumero. These include examples on how to use the interfaces to NLPs, block-algebra-classes and also examples on implementations of nonlinear programming algorithms.

The following subdirectories are not intended to be used directly by the users

- pynumero.extensions: contains the Ctypes interfaces to HSL and ASL. 
- pynumero.cmake: contains the cmake project to build precompiled libraries. Currently these can be obtained from conda-forge without the need for users to compile in their local machines. 

Finally, all code has been documented with docstrings. User documentation as well as api-documentation can be build using sphinx and the .rst files located in pynumero.doc. Instructions on how to build the documentation are available in pynumero/doc/README

Given the size of the PR I suggest looking at the documentation first and go through each of the main subdirectories accordingly. 

@jsiirola, @carldlaird, @blnicho, @michaelbynum  

## Changes proposed in this PR:
-
-

### Legal Acknowledgement

By contributing to this software project, I agree to the following terms and conditions for my contribution:

1. I agree my contributions are submitted under the BSD license.
2. I represent I am authorized to make the contributions and grant the license. If my employer has rights to intellectual property that includes these contributions, I represent that I have received permission to make contributions and grant the required license on behalf of that employer.

### CODE REVIEW

**Comment by blnicho** [comment]
Task list to manage reviewing this PR
- [ ] Review API docs (@michaelbynum)
- [ ] Review (non-API) docs (@blnicho)
- [ ] Review interfaces code
- [ ] Review linear algebra code
- [ ] Review solver code
- [ ] Review examples code
- [ ] Review extensions code
- [ ] Review sparse code

**Comment by santiagoropb** [comment]
Has there been any progress on this PR?

**Comment by michaelbynum** [comment]
@santiagoropb Yes, we are making progress slowly but surely. It is a big PR. Give us a little more time.

**Comment by blnicho** [comment]
We're going to break this into smaller pieces.

**Pull request closed without merging**
