### PR TITLE
Benders MPI logic bug and parallel test coverage

### PR DESCRIPTION
**Pull request by cpmuir**
This PR aims to address an MPI logic bug the issue originally noted in https://github.com/Pyomo/pyomo/pull/1200 and to expand testing for contrib.benders to cover parallel use cases.

By contributing to this software project, I agree to the following terms and conditions for my contribution:

1. I agree my contributions are submitted under the BSD license.
2. I represent I am authorized to make the contributions and grant the license. If my employer has rights to intellectual property that includes these contributions, I represent that I have received permission to make contributions and grant the required license on behalf of that employer.

### CODE REVIEW

**Comment by jsiirola** [comment]
We are waiting for #1285 to set up a workflow for MPI testing through girhub actions.

**Comment by michaelbynum** [comment]
@cpmuir Are `par_farmer.py`, `par_grothkey.py`, and `par_4scen_farmer.py` needed anymore? Aren't all of these copied into `test_benders.py`?

**Comment by cpmuir** [comment]
> @cpmuir Are `par_farmer.py`, `par_grothkey.py`, and `par_4scen_farmer.py` needed anymore? Aren't all of these copied into `test_benders.py`?

No they shouldn't be needed at this point, everything was moved into test_benders.

**Comment by michaelbynum** [comment]
@jsiirola Can we categorize a test as both "mip" and "nightly"? Will that work? Right now, we have the exact same tests but categorized differently so that one set of tests gets run in serial and one set gets run in parallel.

**Comment by jsiirola** [comment]
@michaelbynum, yes:
```python
@unittest.category('mpi','nightly')
```

**Comment by michaelbynum** [comment]
@jsiirola Thanks

**Comment by michaelbynum** [comment]
Okay, I think this is ready. I am happy with the changes, but I think it would be a good idea for one other person to review this.

**Comment by jsiirola** [comment]
The one test failure in Jenkins was due to a fragile test and is not due to this PR.

**Pull request merged**
