### PR TITLE
HierarchicalTimer: use constant indentation for very long lines

### PR DESCRIPTION
**Pull request by jsiirola**
## Summary/Motivation:
This updates the hierarchical timer to use constant indentation (instead of the total field width) when using the total field width would result in lines longer than 200 characters.  This provides more readable output (e.g., when outputting timing information for models with deep block hierarchies).  For example:

```
Identifier                                                                        ncalls   cumtime   percall      %
-------------------------------------------------------------------------------------------------------------------
allallallallallallallallallallallallallallallallallallallallallallallallall            1     0.187     0.187  100.0
    ---------------------------------------------------------------------------------------------------------------
    aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa       10     0.167     0.017   89.2
        -----------------------------------------------------------------------------------------------------------
        aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa                                      50     0.064     0.001   38.3
        abababababababababababababababababababab                                      10     0.000     0.000    0.0
        other                                                                        n/a     0.103       n/a   61.7
        ===========================================================================================================
    other                                                                            n/a     0.020       n/a   10.8
    ===============================================================================================================
===================================================================================================================
```

## Changes proposed in this PR:
- switch the HierarchicalTimer string report to indent by 4 spaces when not doing so would result in lines longer than 200 characters.

### Legal Acknowledgement

By contributing to this software project, I have read the [contribution guide](https://pyomo.readthedocs.io/en/stable/contribution_guide.html) and agree to the following terms and conditions for my contribution:

1. I agree my contributions are submitted under the BSD license.
2. I represent I am authorized to make the contributions and grant the license. If my employer has rights to intellectual property that includes these contributions, I represent that I have received permission to make contributions and grant the required license on behalf of that employer.

### CODE REVIEW

**Review by michaelbynum — APPROVED** [review]
This is awesome! Looks much better this way.

**Comment by jsiirola** [comment]
@michaelbynum Note that this does not change the output formatting until the lines start getting "too long" (where "too long" was arbitrarily hard-coded at 200 characters).  I suppose at some point we should revisit/debate what that threshold really should be.

**Comment by michaelbynum** [comment]
Do you think the indentation should always be 4 spaces?

**Comment by jsiirola** [comment]
> Do you think the indentation should always be 4 spaces?

I don't have a strong opinion, apart from I *do* think it should be 4 if the alternative is really, really long output lines.   For "normal" usage (relatively shallow trees with short identifiers), I don't really have a strong preference.

**Comment by michaelbynum** [comment]
The one failing test is unrelated and intermittent.

**Pull request merged**
