### PR TITLE
Documentation Tweaks for contrib.alternative_solutions

### PR DESCRIPTION
**Pull request by viens-code**
## Fixes # .
Adds documentation details to contrib.alternative_solutions 
## Summary/Motivation:
Adds documentation details to contrib.alternative_solutions 

## Changes proposed in this PR:
- Adds citation to contrib/alternative_solutions/balas.py to original Balas 1972 paper "Canonical Cuts on the Unit Hypercube"
- Adds example to documentation for alternative_solutions demonstrating how to use ``abs_opt_gap`` to limit generated solutions to those within a given optimality gap

### Legal Acknowledgement

By contributing to this software project, I have read the [contribution guide](https://pyomo.readthedocs.io/en/stable/contribution_guide.html) and agree to the following terms and conditions for my contribution:

1. I agree my contributions are submitted under the BSD license.
2. I represent I am authorized to make the contributions and grant the license. If my employer has rights to intellectual property that includes these contributions, I represent that I have received permission to make contributions and grant the required license on behalf of that employer.

### CODE REVIEW

**Comment by mrmundt** [comment]
@viens-code - Please install the most recent version of `black` into your environment and run `black -S -C` on your files.

**Comment by mrmundt** [comment]
@viens-code - `black` is still not your friend. Please make sure you have the most recent version installed and try again.

**Comment by emma58** [comment]
@mrmundt @viens-code I think black passed--this one's a typo.

**Comment by mrmundt** [comment]
@viens-code - Whooops, you're right, sorry, I was looking at the last job. Fix the typo, commit, push, and it'll keep going!

**Comment by viens-code** [comment]
Yeah, I think I figured out what were the issues with black.
Hopefully things work now.
Didn't expect it to spell check my comments "Cannonical" is apparently not the canonical spelling for that word

**Comment by jsiirola** [comment]
@viens-code, can you make this PR against the `doc-reorg` branch instead on `main`? Merging this here would cause a bunch of merge conflicts with that effort.

**Comment by viens-code** [comment]
Closed in favor of #3370  per @jsiirola request to move branch

**Pull request closed without merging**
