### PR TITLE
DON'T MERGE - Trying to debug Travis run times

### PR DESCRIPTION
**Pull request by blnicho**
## Changes proposed in this PR:
-
-

### Legal Acknowledgement

By contributing to this software project, I have read the [contribution guide](https://pyomo.readthedocs.io/en/stable/contribution_guide.html) and agree to the following terms and conditions for my contribution:

1. I agree my contributions are submitted under the BSD license.
2. I represent I am authorized to make the contributions and grant the license. If my employer has rights to intellectual property that includes these contributions, I represent that I have received permission to make contributions and grant the required license on behalf of that employer.

### CODE REVIEW

**Comment by mrmundt** [comment]
@blnicho - It now actually has a fix in it, so could you be convinced to merge it?

**Comment by blnicho** [comment]
Do we want this to be the fix or would it be better to rebuild the docker files?

**Comment by jsiirola** [comment]
My opinion would be to fix this in the docker images themselves.

**Comment by mrmundt** [comment]
Can do! I'll go update the docker script.

**Pull request closed without merging**
