### PR TITLE
Add sphinx documentation for GAMS interface

### PR DESCRIPTION
**Pull request by gseastream**
## Summary/Motivation:
A few months ago a StackOverflow user described the documentation for this interface as "effectively non-existent," so this is to provide a page one can point to in order to view all the options available to the solver. There's also some updates to the current GAMS documentation (and some import cleanup in `GAMS.py` that I forgot to put in a separate commit).

### Legal Acknowledgement

By contributing to this software project, I agree to the following terms and conditions for my contribution:

1. I agree my contributions are submitted under the BSD license.
2. I represent I am authorized to make the contributions and grant the license. If my employer has rights to intellectual property that includes these contributions, I represent that I have received permission to make contributions and grant the required license on behalf of that employer.

### CODE REVIEW

**Comment by qtothec** [comment]
Is there a GAMS.rst page already? I don't remember there being one.

**Comment by gseastream** [comment]
Whoops, still figuring out this new git plugin :P

**Comment by qtothec** [comment]
Also, just making sure that you're aware of @blnicho and @DLWoodruff's ongoing effort to reorganize the Sphinx documentation: https://github.com/Pyomo/pyomo/wiki/Proposed-Sphinx-Documentation-Outline

**Comment by gseastream** [comment]
Thanks for the heads up

**Comment by qtothec** [comment]
@DLWoodruff Tests passing is waiting on #517

**Pull request merged**
