### PR TITLE
Travis docker

### PR DESCRIPTION
**Pull request by ghackebeil**
This PR configures Travis CI to run Pyomo tests using custom DockerHub images that have been built with software we are currently re-installing for each job (e.g., with conda). This new configuration replaces most of that setup time (~5-8 minutes) with the time it takes to pull an image from DockerHub (~1 minute). It also adds working PyPy 2 and 3 builds (previously we could not set these up because of incompatibilities with conda) as well as Anaconda 2 and 3 builds.

It also includes a CPython 3.7 release candidate build. I recently discovered changes that were required in PySP for 3.7 support because of this testing (async was being used as a keyword, but it becomes a reserved word in 3.7).

Builds included:
 - CPython:
   - 3.7-rc [nightly]
   - 3.6.5   [nightly]
   - 3.6.5   [nightly, no-extras]
   - 3.6.5   [parallel]
   - 3.5.5   [nightly]
   - 2.7.15  [nightly, key_job]
   - 2.7.15  [parallel]
 - PyPy:
   - 3.5.3 (6.0.0) [nightly]
   - 2.7.13 (6.0.0) [nightly]
 - Anaconda:
    - 3.6.4 [nightly]
    - 2.7.14 [nightly]

Solvers Included:
 - ~~cplex 12.8 (full)~~
 - ~~cplexamp 12.6.3 (student)~~
 - ~~gurobi_ampl 7.5.0 (student)~~
 - cbc 2.9.9
 - ipopt 3.12.9
 - glpk 4.65
 - gams 25.0.3 (trial, python bindings available on non-PyPy 2.7 and 3.6)
 - ~~baron 18.5.9 (trial)~~

Additional software / libraries:
 - gsl 2.1
 - gjh
 - glj_asl_json

Additional notes:
 - PyPy builds are *much* slower than CPython when coverage is activated, so I've disabled coverage on those builds.
 - I have working install scripts that could insert additional commercial solvers (e.g., gurobi, cplex, baron) into the docker images, but there are licensing issues that still need to be worked out, so these are excluded for now.
 - I still own the public GitHub [repo](https://github.com/ghackebeil/build_docker) that uses Travis CI to build the Docker images as well as the private DockerHub repo that stores the images. This can be reconfigured at any point in the future if we want to place the two repositories under some official Pyomo accounts.

### Legal Acknowledgement

By contributing to this software project, I agree to the following terms and conditions for my contribution:

1. I agree my contributions are submitted under the BSD license.
2. I represent I am authorized to make the contributions and grant the license. If my employer has rights to intellectual property that includes these contributions, I represent that I have received permission to make contributions and grant the required license on behalf of that employer.

### CODE REVIEW

**Comment by ghackebeil** [comment]
I think this is ready to merge. Anyone have any questions or concerns?

**Comment by gseastream** [comment]
I'm not sure exactly how the Docker images work but I noticed your comment in the initial PR that the GAMS python bindings are only available on certain images. Earlier today I found a typo in the current version of the travis setup script in the master branch that was never installing the python bindings instead of selectively installing the python bindings. Previously the python api caused segfaults whenever extras were installed so it was supposed to skip those. I decided to try it on all travis test versions by always installing it and it seems to work without issue on all of them now. This took place in PR #510 with commit [631b263](https://github.com/Pyomo/pyomo/pull/510/commits/631b263739608f42e69973fd8a62acae78eaf34c). I mention this in case this means you need to change some of the Docker images to install the python bindings now.

**Comment by ghackebeil** [comment]
@gseastream: I'm currently [installing](https://github.com/ghackebeil/build_docker/blob/master/install_scripts/gams.sh) the GAMS Python bindings in every Python version that it supports. I'll update the PR description to be more specific.

**Comment by ghackebeil** [comment]
Yes. The PySP changes would be necessary if cplex_ampl (student) were to be included in the images (which it very easily could be, but I don't think we need to get into that license discussion just now). There's also a fix for a cryptic test failure that would happen when networkx was not installed, but it's hardly worth discussing.

**Comment by jsiirola** [comment]
@ghackebeil: I meant to ask: what is the plan / process for keeping the Docker images up-to-date?  Is this going to happen automatically? Otherwise, what triggers the image rebuild?

**Comment by ghackebeil** [comment]
Right now updates to the images would only be triggered by commits to the GitHub repo (i.e., because we noticed a new Python or solver version came out). Perhaps we could setup a cron job on Travis to rebuild these monthly or something though. Some of the solver install scripts pull from a generic "current" url, but not all of them.

Whatever the case, even if we were to review these builds once a year and update to the latest version of everything, we would still be lightyears ahead of the solver versions we're getting on conda as well as the Python versions we're getting natively with Travis.

**Comment by gseastream** [comment]
If you're curious, your GAMS version is already outdated. Latest version is 25.1.1 (May 19, 2018).

They seem to release a new version about twice a year. But this doesn't matter too much for accurate testing.

**Comment by ghackebeil** [comment]
Good to know. Ideally, the GitHub repo would be something anyone on the Pyomo team could push to in order to make small updates like this. So hopefully we'll be at a point soon to allow that.

**Comment by qtothec** [comment]
This seems to have broken travis tests? I'm seeing an error `The command "echo "$DOCKERHUB_PASSWORD" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin" failed and exited with 1 during .`

**Comment by gseastream** [comment]
I'm gonna try merging these changes and see if it helps

**Comment by qtothec** [comment]
Yeah, looks like merging in the changes does the trick. I'm assuming that there was some Travis configuration change in the background requiring the changes from this PR.

**Comment by gseastream** [comment]
Sounds like we need to advice all current PRs to merge these changes too so testing can proceed.

**Comment by qtothec** [comment]
Update on the testing: it looks like PRs from forks are failing, but PRs from the main repo are running properly.

**Pull request merged**
