### PR TITLE
Resolve errors in LaTeX printer for set operations / multidimensional sets

### PR DESCRIPTION
**Pull request by jsiirola**
## Summary/Motivation:
This resolves errors in the `latex_printer()` for models with set operators (in particular, `SetProduct` indexing sets) and multidinensional sets.

## Changes proposed in this PR:
- minor performance improvements in internal lookups
- resolve errors naming `IndexTemplate` objects for multidimensionsl sets
- resolve overlapping placeholder IDs for models with > 10 vars or params
- pull out some embedded constants (make it easier to override)
- Improved output of anonymous set expressions
- add test of pmedian (which motivated these changes)

### Legal Acknowledgement

By contributing to this software project, I have read the [contribution guide](https://pyomo.readthedocs.io/en/stable/contribution_guide.html) and agree to the following terms and conditions for my contribution:

1. I agree my contributions are submitted under the BSD license.
2. I represent I am authorized to make the contributions and grant the license. If my employer has rights to intellectual property that includes these contributions, I represent that I have received permission to make contributions and grant the required license on behalf of that employer.

### CODE REVIEW

**Review by codykarcher — APPROVED** [review]

**Review by mrmundt — APPROVED** [review]
Does this do anything to address issues reported in #3121 ?

**Comment by mrmundt** [comment]
NEOS is having some issues today, it appears.

**Comment by jsiirola** [comment]
> Does this do anything to address issues reported in #3121 ?

Nope: #3121 is asking for support of block structured models That will be a separate PR (this is addressing indexing issues.

**Comment by jsiirola** [comment]
Coverage failure is a codecov issue: the latex_printer is covered at over 92%,

**Pull request merged**
