### PR TITLE
Replicating changes from #444

### PR DESCRIPTION
**Pull request by whart222**
## Summary/Motivation:
Resolving GAMS power() writing issues.

## Changes proposed in this PR:
This PR re-applies the changes in #444 to the merges master.

### Legal Acknowledgement

By contributing to this software project, I agree to the following terms and conditions for my contribution:

1. I agree my contributions are submitted under the BSD license.
2. I represent I am authorized to make the contributions and grant the license. If my employer has rights to intellectual property that includes these contributions, I represent that I have received permission to make contributions and grant the required license on behalf of that employer.

### CODE REVIEW

**Comment by jsiirola** [comment]
Closing this PR in favor of #454, which reopens #444 but targets the merge to master.

**Comment by jsiirola** [comment]
@qtothec: are the changes in b64db64 also applied to your gams_writer_fix branch?  That is, does #454 supersede this branch (so we can delete gams_power_expr, even with unmerged changed)?

**Comment by qtothec** [comment]
Yes, I believe that they are.

**Comment by jsiirola** [comment]
Great ... I'm deleting this branch, then.

**Pull request closed without merging**
