### PR TITLE
Updating CHANGELOG in preparation for the Pyomo 5.6 release

### PR DESCRIPTION
**Pull request by blnicho**
## Summary/Motivation:
First pass at updating the CHANGELOG for the upcoming Pyomo 5.6 release. These changes are based on PRs that have been merged since the last release. I included almost every PR so I welcome suggestions on things to remove.

### Legal Acknowledgement

By contributing to this software project, I agree to the following terms and conditions for my contribution:

1. I agree my contributions are submitted under the BSD license.
2. I represent I am authorized to make the contributions and grant the license. If my employer has rights to intellectual property that includes these contributions, I represent that I have received permission to make contributions and grant the required license on behalf of that employer.

### CODE REVIEW

**Comment by jsiirola** [comment]
This is a great summary, but I wonder if we should summarize/compress it more?  Especially since one of the biggest changes in this release (the new expression system) isn't prominently featured.  I can try and make a stab at condensing things later tonight if you want.

**Comment by blnicho** [comment]
@jsiirola I completely agree that it should be condensed more but I didn't have good notion of relative importance of some PRs compared to others. I figured it was easier to cull stuff after the fact then sift through everything again to see what was missed.

**Comment by blnicho** [comment]
Here is the magic command for finding relevant closed PRs to include in the changelog courtesy of @jsiirola:
`is:pr is:closed merged:>=2018-04-14 base:master sort:updated-desc `

Including as a comment here for future reference.

**Comment by blnicho** [comment]
@jsiirola I've updated the changelog with all the PRs merged since October. Could you take a first pass at condensing it?

**Pull request merged**
