### PR TITLE
PyNumero PyomoNLP should expose nl file options

### PR DESCRIPTION
**Pull request by michaelbynum**
## Changes proposed in this PR:
- PyNumero PyomoNLP should write NL file with skip_trivial_constraints=True

### Legal Acknowledgement

By contributing to this software project, I have read the [contribution guide](https://pyomo.readthedocs.io/en/stable/contribution_guide.html) and agree to the following terms and conditions for my contribution:

1. I agree my contributions are submitted under the BSD license.
2. I represent I am authorized to make the contributions and grant the license. If my employer has rights to intellectual property that includes these contributions, I represent that I have received permission to make contributions and grant the required license on behalf of that employer.

### CODE REVIEW

**Review by blnicho — COMMENTED** [review]
@michaelbynum could you expand the PR description to include the motivation or issue behind this PR? It seems like this will change some default behavior in PyNumero and I'm a little surprised you didn't have to update any tests.

**Comment by michaelbynum** [comment]
I should not have done this in such a hurry. What I really wanted was to be able to specify options to the nl writer.

**Comment by michaelbynum** [comment]
With the most recent changes, the default behavior won't change. However, I should still answer your question. I think the "trivial constraints" (when all of the variables in a constraint are fixed) case is not a terribly common edge case. Also, I'm sure we don't have any tests with trivial constraints. I'm not sure those tests would even belong in PyNumero or not. They might be more appropriate for algorithms developed on top of PyNumero. I'm not sure.

**Review by jsiirola — APPROVED** [review]
Seems reasonable to me.

**Review by blnicho — APPROVED** [review]

**Pull request merged**
