### PR TITLE
[IDEA] Drafting new expression system

### PR DESCRIPTION
**Pull request by RomeoV**
## Disclaimer:
_This is a draft and is still far from being finished and fleshed out. I am posting this pull request mostly to allow further discussion on the code. Additionally, since I am writing this as part of my thesis, I most likely won't have the time to finish all the ToDos that could be done (see below for list). I am aiming to bring this to a reasonable and usable form that is useful in solving new problems or at least modeling problems in a more natural way._

## ~Fixes~
No issue assigned

## Summary/Motivation:
There are many occurrences in the code where logical conditions play a role. My main motivation comes from the 'General Disjunctive Programming' part, that has possible logical relations in the formulation. These logical relations can currently not be modeled.
With the introduction of this system, the GDP formulation can finally be modeled completely.  Furthermore, it can handle the relations between disjuncts more naturally than the current formulation. 

## Changes proposed in this PR:
- Implementation of a tree structure supporting various logical expressions
- An algorithm to bring an arbitrary tree into [Conjunctive Normal Form](https://en.wikipedia.org/wiki/Conjunctive_normal_form)
- An algorithm that transforms a logical expression tree in CNF into linear constraints in the pyomo model
- Tests covering a fair amount of the code functionality
  - This includes unit tests and simple models with and without simple disjunctions (solved with `baron`)
  - There are still some bugs in the code that need to get tested for (but will there ever not be?)
- Implementation of an example using the logical expression system

## Open ToDos
Listed roughly in order of importance
- [x] `XOrNode`
- [x] `IffNode` (equivalence)
- [x] more rigorous unit testing (there are still some bugs for special cases)
- [x] larger example model (maybe from literature)

Those are the ones I plan on finishing this week (hopefully). There is a lot more to do, I would like to have some discussion about the code/structure with someone before I tackle the following problems though:
- [ ] Introduction of `BooleanVar`
- [ ] Replacing disjunct logic with this expression system
- [ ] Creating some kind of parser that's easier to use than the current one
- [ ] Storing the logic tree in the model instead of just the transformed constraints
- [ ] Bringing the whole tree structure into a structure more resembling the current expression system structure (i.e. replace `NumericalValue`, etc)

### Legal Acknowledgement

By contributing to this software project, I agree to the following terms and conditions for my contribution:

1. I agree my contributions are submitted under the BSD license.
2. I represent I am authorized to make the contributions and grant the license. If my employer has rights to intellectual property that includes these contributions, I represent that I have received permission to make contributions and grant the required license on behalf of that employer.

### CODE REVIEW

**Comment by qtothec** [comment]
@RomeoV is this still WIP or did you want us to review this?

**Comment by RomeoV** [comment]
I wrote a bunch of tests that check the expression system. I am not 100% confident though that the automatic code coverage system finds and executes the tests. The tests are found in
`pyomo/pyomo/contrib/logical_expression_system/tests`
Can someone affirm that the tests are found?

**Comment by qtothec** [comment]
Is there a compelling reason for naming `IfNode` rather than `ImpliesNode`?

**Comment by jsiirola** [comment]
This has been subsumed by #1115.

**Pull request closed without merging**
