### PR TITLE
Remove the PICO solver interface

### LINKED ISSUE #178: Deprecate the PICO interface
Include the solver interface, tests, etc.

PICO is not currently being supported, and we don't test it on any platforms.

### PR DESCRIPTION
**Pull request by jsiirola**
## Summary/Motivation:
The PICO solver interface hasn't been tested or maintained in more than 5 years, and I do not even know where to get the PICO solver to test against any more.  This removes the PICO interface from Pyomo.

Note that this does not have a deprecation path (and we have technically never announced that PICO support is deprecated).  We may not want to merge this PR without a deprecation period.

## Changes proposed in this PR:
- Remove PICO interface from Pyomo

### Legal Acknowledgement

By contributing to this software project, I have read the [contribution guide](https://pyomo.readthedocs.io/en/stable/contribution_guide.html) and agree to the following terms and conditions for my contribution:

1. I agree my contributions are submitted under the BSD license.
2. I represent I am authorized to make the contributions and grant the license. If my employer has rights to intellectual property that includes these contributions, I represent that I have received permission to make contributions and grant the required license on behalf of that employer.

### CODE REVIEW

**Review by michaelbynum — APPROVED** [review]
The PR looks good. I have no preference on whether or not we have a deprecation period.

**Comment by jsiirola** [comment]
I just looksed farther into this.  While we did not emit a deprecation warning, we *did* make it so that the PICO solver was unable to automatically locate the `pico` executable.  Any user using PICO has had to manually set the path to the solver.  Given that no one ever asked us about this behavior, I suspect that it is save to delete the interface.

**Comment by mrmundt** [comment]
@jsiirola , @michaelbynum - The jenkins failure is not real. It's an intermittent MOSEK license unavailability.

**Review by blnicho — APPROVED** [review]

**Comment by jsiirola** [comment]
Should we hold off on merging this until after 6.3.1?

**Comment by blnicho** [comment]
I vote to include this in 6.3.1.

**Pull request merged**
