### PR TITLE
Move pyutilib.misc.timing into pyomo.common.timing

### PR DESCRIPTION
**Pull request by mrmundt**
## Summary/Motivation:
To prepare for Pyomo's 6.0 release, we would like to do our best to move PyUtilib dependencies into Pyomo. This is the beginning of that work - moving pyutilib.misc.timing into pyomo.common.timing.

## Changes proposed in this PR:
- Add `pyutilib.misc.timing` code into `pyomo.common.timing`
- Update all references to `pyutilib.misc.timing`

### Legal Acknowledgement

By contributing to this software project, I have read the [contribution guide](https://pyomo.readthedocs.io/en/stable/contribution_guide.html) and agree to the following terms and conditions for my contribution:

1. I agree my contributions are submitted under the BSD license.
2. I represent I am authorized to make the contributions and grant the license. If my employer has rights to intellectual property that includes these contributions, I represent that I have received permission to make contributions and grant the required license on behalf of that employer.

### CODE REVIEW

**Comment by mrmundt** [comment]
@jsiirola @blnicho - As far as I can tell, `timing` was never tested in `pyutilib`. So the only thing this PR is really missing is some extra timing tests, if someone wants to create them.

**Comment by mrmundt** [comment]
@blnicho @jsiirola - Win/3.8 was stuck on installing GAMS. I preemptively killed it because it had been hanging there for over 2 hours already.

**Review by jsiirola — APPROVED** [review]

**Comment by jsiirola** [comment]
@mrmundt: I made a bunch of changes to the timing to get things to both me a little more robust and to improve coverage.  If you like the changes, then I thing this is good for you to merge.

**Comment by mrmundt** [comment]
> @mrmundt: I made a bunch of changes to the timing to get things to both me a little more robust and to improve coverage. If you like the changes, then I think this is good for you to merge.

Looks good to me, John! Thanks for making the changes. You or @blnicho will have to click the merge button, though.

**Pull request merged**
