### PR TITLE
Pynumero 

### PR DESCRIPTION
**Pull request by santiagoropb**
## Summary/Motivation:
Add PyNumero to pyomo.contrib. PyNumero is a python package for numerical optimization that provides a high-level programming framework for rapid development of nonlinear optimization algorithms. The package gives access to all high-level features of the python programming language without making large sacrifices on computational performance. It combines the capabilities of Pyomo with libraries like the AMPL Solver Library (ASL), The Harwell Subroutine (HSL) (optional), and NumPy/SciPy. PyNumero performs all linear algebra operations in compiled code, and is designed to avoid marshalling of data between the C and the Python environments.

## Changes proposed in this PR:
-
-

### Legal Acknowledgement

By contributing to this software project, I agree to the following terms and conditions for my contribution:

1. I agree my contributions are submitted under the BSD license.
2. I represent I am authorized to make the contributions and grant the license. If my employer has rights to intellectual property that includes these contributions, I represent that I have received permission to make contributions and grant the required license on behalf of that employer.

### CODE REVIEW

**Comment by santiagoropb** [comment]
@carldlaird @jsiirola please review this pull request. I am still waiting for conda-forge to take the pull request for the libraries. Once that's done I will send you the link. For now, libraries need to be compiled manually using the cmake project that is under pyomo/contrib/pynumero/cmake. Instructions are provided in the readme and also in the sphinx documentation that is under pyomo/contrib/pynumero/doc. The unittests that are currently in place check for the availability of the libraries. If pynumero libraries are not found, tests using asl or sparseutils are skipped.

**Comment by santiagoropb** [comment]
@jsiirola  most of the tests here are being skipped given the fact that we are not including the shared libraries in the branch. However, the coverage with the libraries is as follows:

`pyomo/contrib/pynumero/extensions/__init__.py                               0      0   100%
pyomo/contrib/pynumero/extensions/asl.py                                  161     21    87%
pyomo/contrib/pynumero/extensions/hsl.py                                   56     39    30%
pyomo/contrib/pynumero/extensions/sparseutils.py                           40      6    85%
pyomo/contrib/pynumero/extensions/utils.py                                 28     12    57%
pyomo/contrib/pynumero/interfaces/__init__.py                               7      2    71%
pyomo/contrib/pynumero/interfaces/nlp.py                                  803    237    70%
pyomo/contrib/pynumero/interfaces/nlp_compositions.py                     393     67    83%
pyomo/contrib/pynumero/interfaces/nlp_transformations.py                  177     33    81%
pyomo/contrib/pynumero/linalg/__init__.py                                   0      0   100%
pyomo/contrib/pynumero/linalg/solvers/__init__.py                           7      2    71%
pyomo/contrib/pynumero/linalg/solvers/ma27_solver.py                      118    106    10%
pyomo/contrib/pynumero/sparse/__init__.py                                  22      8    64%
pyomo/contrib/pynumero/sparse/base.py                                      16      3    81%
pyomo/contrib/pynumero/sparse/block_matrix.py                             615    250    59%
pyomo/contrib/pynumero/sparse/block_vector.py                             412    123    70%
pyomo/contrib/pynumero/sparse/coo.py                                      323     93    71%
pyomo/contrib/pynumero/sparse/csc.py                                      256    135    47%
pyomo/contrib/pynumero/sparse/csr.py                                      255    113    56%
pyomo/contrib/pynumero/sparse/extract.py                                   21      2    90%
pyomo/contrib/pynumero/sparse/utils.py                                    108     67    38%`

I will add some additional tests in block_matrix, csr, coo and utils which are the ones with relatively low coverage. I am still waiting for the merge of the pull request of pynumero_libraries in conda-feedstock. However, I expect that to be merged this week. Once we have that we can use it to make sure the libraries are available when running tests in travis. Alternatively we can use some of the wget functionality you suggested some time ago.

**Comment by santiagoropb** [comment]
@jsiirola after working on tests the new coverage with the libraries is as follows

pyomo/contrib/pynumero/__init__.py                                          0      0   100%
pyomo/contrib/pynumero/examples/__init__.py                                 0      0   100%
pyomo/contrib/pynumero/extensions/__init__.py                               0      0   100%
pyomo/contrib/pynumero/extensions/asl.py                                  161     21    87%
pyomo/contrib/pynumero/extensions/sparseutils.py                           44      2    95%
pyomo/contrib/pynumero/extensions/utils.py                                 24      9    62%
pyomo/contrib/pynumero/interfaces/__init__.py                               7      2    71%
pyomo/contrib/pynumero/interfaces/nlp.py                                  781     69    91%
pyomo/contrib/pynumero/interfaces/nlp_compositions.py                     393     67    83%
pyomo/contrib/pynumero/interfaces/nlp_transformations.py                  177     33    81%
pyomo/contrib/pynumero/sparse/__init__.py                                  22      8    64%
pyomo/contrib/pynumero/sparse/base.py                                      16      3    81%
pyomo/contrib/pynumero/sparse/block_matrix.py                             586    113    81%
pyomo/contrib/pynumero/sparse/block_vector.py                             412    123    70%
pyomo/contrib/pynumero/sparse/coo.py                                      300     53    82%
pyomo/contrib/pynumero/sparse/csc.py                                      236     27    89%
pyomo/contrib/pynumero/sparse/csr.py                                      261     56    79%
pyomo/contrib/pynumero/sparse/extract.py                                   21      2    90%
pyomo/contrib/pynumero/sparse/utils.py                                     56     12    79%

**Comment by blnicho** [comment]
Closing this, it is superseded by #725

**Pull request closed without merging**
