### PR TITLE
Bugfix for GDP var mover

### PR DESCRIPTION
**Pull request by qtothec**
## Summary/Motivation:
Deactivate disjunctions nested in deactivated Disjuncts.
Also, some re-ordering of imports because of my IDE.

### Legal Acknowledgement

By contributing to this software project, I agree to the following terms and conditions for my contribution:

1. I agree my contributions are submitted under the BSD license.
2. I represent I am authorized to make the contributions and grant the license. If my employer has rights to intellectual property that includes these contributions, I represent that I have received permission to make contributions and grant the required license on behalf of that employer.

### CODE REVIEW

**Comment by jsiirola** [comment]
@qtothec: how do you get to a situation where you would need this?  Shouldn't the nested Disjunctions have already been deactivated when they were relaxed -- as we relax things from the bottom up?  If there are still active Disjunctions, quietly deactivating them will take an invalid model and make it appear valid, right?

**Comment by qtothec** [comment]
@jsiirola Yes, unless what you do is create a disjunction, and deactivate all of the disjuncts in the disjunction for a specific case study... is the empty Disjunction object that is left still active?

**Comment by jsiirola** [comment]
In that case, I think it is only acceptable to deactivate a Disjunction when all the Disjuncts are themselves deactivated.

**Comment by qtothec** [comment]
@jsiirola I'm adding a test for which that check does not work.

```
m = ConcreteModel()
m.d1 = Disjunct()
m.d1.d1 = Disjunct()
m.d1.d2 = Disjunct()
m.d1.disj = Disjunction(expr=[m.d1.d1, m.d1.d2])
m.d2 = Disjunct()
m.disj = Disjunction(expr=[m.d1, m.d2])
m.d1.deactivate()
TransformationFactory('gdp.bigm').apply_to(m)
# for disj in m.component_data_objects(Disjunction, active=True):
#     print(disj.name)
# There should be no active Disjunction objects.
self.assertIsNone(
    next(m.component_data_objects(Disjunction, active=True), None))
```

**Comment by qtothec** [comment]
Appveyor is only showing failed because of a networking issue for one run.

**Comment by blnicho** [comment]
@qtothec I restarted the Appveyor tests

**Comment by qtothec** [comment]
@jsiirola I know that you didn't like this fix for some reason, but the issue persists: if I have a disjunction in a disjunct and I deactivate that disjunct, that disjunction is left active at the end of the transformation. This is not so unusual to see. If I fathom a disjunct and wish to eliminate it, then I would end up executing the code below.

```
from pyomo.environ import *
from pyomo.gdp import *
m = ConcreteModel()
m.d1 = Disjunct()
m.d1.d1 = Disjunct()
m.d1.d2 = Disjunct()
# Nested disjunction d1.disj
m.d1.disj = Disjunction(expr=[m.d1.d1, m.d1.d2])

m.d2 = Disjunct()
m.disj = Disjunction(expr=[m.d1, m.d2])

# Deactivating the disjunct d1
m.d1.deactivate()
# Applying big M
TransformationFactory('gdp.bigm').apply_to(m)

# Checking for active Disjunctions on the model
for disj in m.component_data_objects(Disjunction, active=True):
    print(disj.name)
# There should be no active Disjunction objects, 
# but this will print the name of m.d1.disj, because it is still active.

# This assertion fails
assert next(m.component_data_objects(Disjunction, active=True),None) is None
```

**Comment by qtothec** [comment]
@jsiirola was there more that you wanted to add on to this?

**Comment by qtothec** [comment]
There's a logic error somewhere. I have deactivated disjuncts which are springing back to life after bigM transformation. Not convinced that they're directly related to this PR, but investigating.

**Pull request merged**
