### PR TITLE
Sphinx Documentation Overhaul

### LINKED ISSUE #370: Fix documentation with invalid use of model.solutions.load_from(results)
@MMeketon pointed in #365 that there are a number of examples in the online docs ([here](https://software.sandia.gov/downloads/pub/pyomo/PyomoOnlineDocs.html)) that are calling `model.solutions.load_from` after an `opt.solve(...)` call that did not set `load_solutions=False`.

In normal termination conditions, a redundant call to `model.solutions.load_from` such as this happens to work due to confusing semantics for `model.solutions.load_from` (which we should fix). 

Even more confusing, the fact that this redundant call is innocuous in normal termination conditions makes it seem like we do not handle situations where the solver stops due to a limit (results.solver.status == SolutionStatus.aborted) but provides a feasible solution. This is because there is a check in `model.solutions.load_from` that (when `results.solver.status == SolutionStatus.aborted` is true), results in
 - a warning if results.solution is not empty,
 - an exception when results.solution is empty.

### LINKED ISSUE #492: Reorganize Sphinx documentation
Our Sphinx documentation needs a significant reorganization. I put together a tentative outline which I will link to this issue and I welcome feedback from the team.

### LINKED ISSUE #493: Rework doc directory
In addition to refactoring the Sphinx documentation in #492, the entire doc directory needs to be reorganized. Many of the files can probably be deleted or archived.

### LINKED ISSUE #682: Recent change broke online docs
I just happened to looking at the Pyomo Network documentation at:

https://pyomo.readthedocs.io/en/latest/modeling_extensions/network.html

and noticed a significant issue that must have been caused by some recent merges. Namely, none of the autoclass generation executed; they are completely missing from the page. I glanced at the DAE page and the issue seems to have affected it there too. I would guess perhaps for some reason the imports in the rst files are failing. But it's even weirder because when I recompile everything locally using an up-to-date master branch, the autoclasses do work (although I notice an import failure with GurobiPersistent, which may or may not be related).

Also there's a typo in line 112, it should read "At the end of the transformation" (the second "the" is missing).

### PR DESCRIPTION
**Pull request by blnicho**
## Summary/Motivation:
This PR is a significant overhaul of the Pyomo Sphinx documentation and cleanup of the doc directory of Pyomo. The existing Sphinx rst files were reorganized to match the new documentation outline (https://github.com/Pyomo/pyomo/wiki/Proposed-Sphinx-Documentation-Outline). The eventual goal is to reconsider the use of spy files in favor of built-in code snippet testing using Sphinx doctests. In the meantime, I copied any spy files or scripts used in the documentation to a new `script_spy_files` directory. All other spy files, old rst files, and random directories in the top level `doc` directory were moved to `doc/attic`. Finally, this PR reworks the readthedocs build to use the master branch of PyUtilib which is required for some of the new PySP documentation. This was done by changing the settings in readthedocs and replacing the `.readthedocs.yml` file with a `.readthedocs_requirements.txt` file.

The new documentation can be previewed [here](https://pyomo.readthedocs.io/en/docconversion/index.html). This is primarily a reorganization of existing files. I did fix a few typos and cleanup some rst formatting but the documentation as a whole still needs a thorough proof-reading. In addition, we should go through the archived files and delete what we can.

This PR fixes #682, fixes #492, fixes #493, and fixes #370  

## Changes proposed in this PR:
- Reorganize Pyomo Sphinx documentation
- Reorganize `doc` directory and archive old files
- Reconfigure readthedocs to install the master branch of PyUtilib

### Legal Acknowledgement

By contributing to this software project, I agree to the following terms and conditions for my contribution:

1. I agree my contributions are submitted under the BSD license.
2. I represent I am authorized to make the contributions and grant the license. If my employer has rights to intellectual property that includes these contributions, I represent that I have received permission to make contributions and grant the required license on behalf of that employer.

### CODE REVIEW

**Comment by blnicho** [comment]
@qtothec yeah, I realized that as soon as I opened the PR. 99% of the changed files are in the `doc` directory. The only exceptions are the minor change in `gdpopt.py` that you made to render the docstring and the readthedocs requirements file mentioned in the PR description. 

The best way to review this is probably to look at the actual documentation and/or look through the entire doc directory in the docconversion branch. The code diff in the PR isn't super helpful.

**Comment by qtothec** [comment]
Looks like we are suffering a random Appveyor failure here

**Comment by blnicho** [comment]
Looks like Appveyor is officially broken again

**Comment by blnicho** [comment]
I received offline comments on this PR from @qtothec and @DLWoodruff and made the requested changes. Every page of the new documentation has been scanned by multiple people for rendering/formatting correctness (which was the main focus of this PR). 

We discussed this PR at the Pyomo Developers meeting yesterday and decided to go ahead with the merge as there are other PRs waiting on this.

**Pull request merged**
