### PR TITLE
Issue#2123 k_aug interface in Pyomo sensitivity toolbox reports wrong anwer

### PR DESCRIPTION
**Pull request by jialuw96**
@adowling2  In pyomo.contrib.sensitivity_toolbox, I added sens.py from IDAES repo as sens_IDAES.py, and a minimal example showing bugs in dc/dx in the file optimize_debug.py

### CODE REVIEW

**Comment by adowling2** [comment]
This PR (will eventually) close #2124. It supersedes PR #2082, which can now be closed.

`optimized_debug.py` shows how the current version of `sens.py` in Pyomo gives incorrect answers.

`sens_IDAES.py` is a copy of `sens.py` found in IDAES. Using the IDAES version of `sens.py`, `k_aug` calculates the correct sensitivities.

`sens_original.py` is a copy of the current version of `sens.py` in Pyomo contrib.

Both `sense_IDAES.py` and `sens_original.py` should be deleted before this PR is merged. We are including them here for convenient reference.

In this PR, we will modify `sens.py` to produce the correct answer for this example. This example should also be added as a unit test.

**Comment by jialuw96** [comment]
Next step:
 -  Add minimal working example of dynamic model with analytical solution 
 - Add minimal working example of Pyomo.DAE version of the dynamic model

**Comment by jialuw96** [comment]
Minimal working example 1: sens_example.py, get_dfds_dcds() has the same (wrong) behavior for sens.py in IDAES and Pyomo. It is missing a non-zero entry.

(Add details about output here)

Minimal working example 2: reactor_sens_minimal.py, get_dsdp() gives different results for sens.py in IDAES and Pyomo. The IDAES version is correct, but the Pyomo version has the code clarity enhancement you have made in the past few months.

(Add details about output here )

**Comment by Robbybp** [comment]
@adowling2 @jialuw96 We're going to close this PR in favor of working out a solution in the discussion of issue #2123. Feel free to re-open a PR if you have a proposed change to resolve the issue.

**Pull request closed without merging**
