### PR TITLE
Skip failing Baron tests

### PR DESCRIPTION
**Pull request by jsiirola**
## Summary/Motivation:
This skips a Baron test that has suddenly (inexplicably) runs for more than 90 minutes on old Baron versions and two tests that fail on newer Baron versions.

## Changes proposed in this PR:
- Skip `pyomo/contrib/pyros/tests/test_grcs.py::RegressionTest::test_higher_order_decision_rules` for Baron < 23.1.5
- Skip `pyomo/contrib/pyros/tests/test_grcs.py::RegressionTest::test_terminate_with_max_iter` for Baron >= 23.1.5
- Skip `pyomo/contrib/pyros/tests/test_grcs.py::testMasterFeasibilityUnitConsistency::test_two_stg_mod_with_axis_aligned_set` for Baron >= 23.1.5

### Legal Acknowledgement

By contributing to this software project, I have read the [contribution guide](https://pyomo.readthedocs.io/en/stable/contribution_guide.html) and agree to the following terms and conditions for my contribution:

1. I agree my contributions are submitted under the BSD license.
2. I represent I am authorized to make the contributions and grant the license. If my employer has rights to intellectual property that includes these contributions, I represent that I have received permission to make contributions and grant the required license on behalf of that employer.

### CODE REVIEW

**Review by emma58 — APPROVED** [review]

**Comment by shermanjasonaf** [comment]
@jsiirola I presume this is occurring with BARON > 22.11.03? I have just updated my local BARON distribution and observed on my PC that the outcomes for `RegressionTest::test_terminate_with_max_iter` and `testMasterFeasibilityUnitConsistency::test_two_stg_mod_with_axis_aligned_set` are sensitive to the BARON distribution (both pass with 22.9.30, but fail with 23.01.05).

**Review by shermanjasonaf — APPROVED** [review]

**Comment by jsiirola** [comment]
I hit this as part of #2693.  The test was hanging with 22.9.30, but not with 23.1.5.  I am also seeing the two failures you mention above with 23.1.5.

**Comment by jsiirola** [comment]
Should we add those two tests to the list of skipped tests until you have a chance at making them more robust?

**Comment by jsiirola** [comment]
@shermanjasonaf: We discussed this at the Dev call today: the current plan is to skip this test + the two new ones that are now failing in 23.1.5, along with adding an issue to revisit and rework the tests so that they work more broadly.

**Comment by shermanjasonaf** [comment]
Noted.

**Pull request merged**
