### PR TITLE
Updated parmest graphics due to recent changes in seaborn

### PR DESCRIPTION
**Pull request by kaklise**
## Summary/Motivation:
Resolves test failures in parmest graphics caused by recent updates to seaborn.  These changes should be compatible with multiple versions of Python.

## Changes proposed in this PR:
-
-

### Legal Acknowledgement

By contributing to this software project, I have read the [contribution guide](https://pyomo.readthedocs.io/en/stable/contribution_guide.html) and agree to the following terms and conditions for my contribution:

1. I agree my contributions are submitted under the BSD license.
2. I represent I am authorized to make the contributions and grant the license. If my employer has rights to intellectual property that includes these contributions, I represent that I have received permission to make contributions and grant the required license on behalf of that employer.

### CODE REVIEW

**Review by DLWoodruff — APPROVED** [review]
This looks good. But why did you add an import sys?

**Comment by kaklise** [comment]
I imported sys to check the python version, and use the updated seaborn function if the version >= 3.6

**Comment by jsiirola** [comment]
Is the correct thing to check the python version, or to check the seaborn version?  There is a utility in `pyomo.common.dependencies` called `_check_version` that you can use to test if a module meets a minimum version.  I can clean it up and make it public to use in this PR if you are interested.

**Comment by kaklise** [comment]
I was unaware of that utility.  Checking the seaborn version makes more sense. If you can clean that up, I'd appreciate it.

**Review by jsiirola — APPROVED** [review]
Looks good, pending successful tests.

**Comment by jsiirola** [comment]
The one failing test is a licensing issue on one of the Jenkins jobs.  This is safe to merge.

**Pull request merged**
