### PR TITLE
Add documentation to public functions, even the deprecated ones. That…

### PR DESCRIPTION
**Pull request by qtothec**
… way, they show up when you do help(Suffix). Otherwise, they just look blank, and I have to go digging.

Also: applied autoPEP8

### CODE REVIEW

**Comment by qtothec** [comment]
Triggering rebuild to see if it will help with #204

**Comment by qtothec** [comment]
You would need to pass it the logger somehow:
```
@deprecated("method 'foo' has been replaced by method 'bar'", logger)
def foo(self, *args):
    # the function...
    pass
```

**Comment by jsiirola** [comment]
You could just grab & use the "global" `pyomo.core` logger:
```
import logging
logging.getLogger('pyomo.core').warn('DEPRECATED: ...')
```

**Comment by qtothec** [comment]
I'll piece together something simple and we can look at it.

**Comment by qtothec** [comment]
@jsiirola How's it look now?

**Comment by jsiirola** [comment]
This is great.  I just added/expanded some of the tests.

**Pull request merged**
