### PR TITLE
appsi nl_writer: better handling of fixed binary vars

### LINKED ISSUE #2375: APPSI-IPOPT: NLWriter currently only supports continuous variables.
## Summary

I using appsi_ipopt to solve fixed-NLP subplem in MindtPy.  
I know that in APPSI-IPOPT, NLWriter currently only supports continuous variables.
I manually tested that NLWriter now can support fixed discrete variables.  For example, the following code works well. 

```
from pyomo.environ import *
from pyomo.contrib.mindtpy.tests.MINLP2_simple import SimpleMINLP as SimpleMINLP2

model = SimpleMINLP2()
TransformationFactory('core.fix_integer_vars').apply_to(model)
opt = SolverFactory('appsi_ipopt')
result = opt.solve(model, tee=True)
print(result)
```

### Steps to reproduce the issue

However, if I change **SimpleMINLP2** to **SimpleMINLP5**, the continuous variables not supported ERROR will be reported.

```
# example.py
from pyomo.environ import *
from pyomo.contrib.mindtpy.tests.MINLP2_simple import SimpleMINLP as SimpleMINLP2
from pyomo.contrib.mindtpy.tests.MINLP5_simple import SimpleMINLP5

model = SimpleMINLP5()
TransformationFactory('core.fix_integer_vars').apply_to(model)
opt = SolverFactory('appsi_ipopt')
result = opt.solve(model, tee=True)
print(result)
```

### Error Message

```console
$ # Output message here, including entire stack trace, if available
Traceback (most recent call last):
  File "/Users/zedongpeng/Github/pyomo-MINLP-benchmarking/test5.py", line 8, in <module>
    result = opt.solve(model, tee=True)
  File "/Users/zedongpeng/Github/pyomo/pyomo/contrib/appsi/base.py", line 1230, in solve
    results: Results = super(LegacySolverInterface, self).solve(model)
  File "/Users/zedongpeng/Github/pyomo/pyomo/contrib/appsi/solvers/ipopt.py", line 264, in solve
    self._writer.write(model, self._filename+'.nl', timer=timer)
  File "/Users/zedongpeng/Github/pyomo/pyomo/contrib/appsi/writers/nl_writer.py", line 187, in write
    self._writer.write(filename)
ValueError: NLWriter currently only supports continuous variables.
```

### Information on your system

Pyomo version: 6.4.1.dev0
Python version: Python 3.7.7
Operating system: MacOS
How Pyomo was installed (PyPI, conda, source):
Solver (if applicable): appsi_ipopt

### PR DESCRIPTION
**Pull request by michaelbynum**
## Summary/Motivation:
The Appsi NL writer does not yet support integer variables. However, fixed integer variables should be fine. This PR ensures that fixed integer variables work in the Appsi NL writer.

### Legal Acknowledgement

By contributing to this software project, I have read the [contribution guide](https://pyomo.readthedocs.io/en/stable/contribution_guide.html) and agree to the following terms and conditions for my contribution:

1. I agree my contributions are submitted under the BSD license.
2. I represent I am authorized to make the contributions and grant the license. If my employer has rights to intellectual property that includes these contributions, I represent that I have received permission to make contributions and grant the required license on behalf of that employer.

### CODE REVIEW

**Review by jsiirola — APPROVED** [review]

**Comment by michaelbynum** [comment]
The test failures are known / unrelated to this PR (and will be addressed by #2400)

**Comment by ZedongPeng** [comment]
Hi @michaelbynum .
If I run the following script, `ValueError: NLWriter currently only supports continuous variables.` will still be reported.
```
# example.py
from pyomo.environ import *
from pyomo.contrib.mindtpy.tests.MINLP2_simple import SimpleMINLP as SimpleMINLP2
from pyomo.contrib.mindtpy.tests.MINLP5_simple import SimpleMINLP5

model = SimpleMINLP5()
TransformationFactory('core.fix_integer_vars').apply_to(model)
opt = SolverFactory('appsi_ipopt')
result = opt.solve(model, tee=True)
print(result)
```

Output:
```
Traceback (most recent call last):
  File "test5.py", line 8, in <module>
    result = opt.solve(model, tee=True)
  File "/Users/zedongpeng/Github/pyomo/pyomo/contrib/appsi/base.py", line 1236, in solve
    results: Results = super(LegacySolverInterface, self).solve(model)
  File "/Users/zedongpeng/Github/pyomo/pyomo/contrib/appsi/solvers/ipopt.py", line 264, in solve
    self._writer.write(model, self._filename+'.nl', timer=timer)
  File "/Users/zedongpeng/Github/pyomo/pyomo/contrib/appsi/writers/nl_writer.py", line 184, in write
    self._writer.write(filename)
ValueError: NLWriter currently only supports continuous variables.
```

**Comment by michaelbynum** [comment]
@ZedongPeng , Did you rebuild the Appsi libraries? I just ran the code you posted, and it ran fine for me.

**Comment by ZedongPeng** [comment]
I forgot to rebuild the APPSI libraries. After rebuilding, it also ran fine for me. Thanks.

**Pull request merged**
