### PR TITLE
Minor Updates to the GAMS Solver

### PR DESCRIPTION
**Pull request by gseastream**
I found more things to update so I made a new branch/pull request. This includes documentation updates, splitting lines over the maximum length, specifying when to check expression evaluation, and adding support for report_timing.

### CODE REVIEW

**Comment by gseastream** [comment]
@qtothec are you referring to the timing reporting? I based that off of OptSolver.

**Comment by qtothec** [comment]
@gseastream Yes. And oh, I see. Good.

**Comment by ghackebeil** [comment]
This seems ready to merge. You guys agree?

**Comment by gseastream** [comment]
Yeah, I think requiring less installation is reason enough since the API does not seem to be faster (maybe slower).

**Pull request merged**
