### PR TITLE
Adding Pyomo.DOE logo files

### PR DESCRIPTION
**Pull request by adowling2**
## Fixes (none)

Please do not merge until #2294 has been merged.

## Summary/Motivation:
- Pyomo.DOE now has a logo!

## Changes proposed in this PR:
- Adding logo files including .png and .ai similar to other logos

### Legal Acknowledgement

By contributing to this software project, I have read the [contribution guide](https://pyomo.readthedocs.io/en/stable/contribution_guide.html) and agree to the following terms and conditions for my contribution:

1. I agree my contributions are submitted under the BSD license.
2. I represent I am authorized to make the contributions and grant the license. If my employer has rights to intellectual property that includes these contributions, I represent that I have received permission to make contributions and grant the required license on behalf of that employer.

### CODE REVIEW

**Comment by adowling2** [comment]
@jialuw96 the logo is on this branch for future presentations, etc.

**Review by mrmundt — APPROVED** [review]

**Comment by mrmundt** [comment]
Not merging! Just approving to streamline merging later.

**Comment by blnicho** [comment]
Converting this to draft/WIP until the Pyomo.DOE PR is merged

**Comment by adowling2** [comment]
@blnicho @kaklise @jsiirola @mrmundt @jialuw96

We now have two versions of the logo.

Version 1:
PyomoDOE-sm

Version 2:
PyomoDoE-sm

Files for both are on GitHub (in folders named version 1 and 2 in this draft PR). Once we decide which one to keep, I'll delete the other one. We'll then have the not used version saved in GitHub history.

I like version 2. I agree with @jsiirola that "DOE" may be confused with "Department of Energy". The only downside is that the official paper has "Pyomo.DOE" in the title. IMO, that is not enough to warrant sticking with version 1. Happy to hear comments from others.

**Comment by adowling2** [comment]
I just finished editing a presentation and I prefer version 2 (Pyomo.DoE). @jialuw96 any thoughts on referring to our package as Pyomo.DoE?

**Comment by jialuw96** [comment]
> I just finished editing a presentation and I prefer version 2 (Pyomo.DoE). @jialuw96 any thoughts on referring to our package as Pyomo.DoE?

I am okay with this change.

**Comment by blnicho** [comment]
@adowling2 @jialuw96 I think the consensus was to go with version 2 of the logo, "Pyomo.DoE". Can you remove version 1 from this PR? Once that's done this will be ready to merge.

**Comment by adowling2** [comment]
Yes, I'll have this ready in 10 minutes.

**Comment by adowling2** [comment]
Now let's see if this breaks the documentation.

**Comment by blnicho** [comment]
@adowling2 looks like the logo was not included in the readthedocs documentation in #2294 so there is nothing to break. Do you plan to add it as part of this PR or add it as another task under #2610?

**Comment by adowling2** [comment]
I say merge this and then a separate PR.

**Review by blnicho — APPROVED** [review]

**Pull request merged**
