### PR TITLE
Jenkins build infrastructure improvements

### PR DESCRIPTION
**Pull request by jsiirola**
## Summary/Motivation:
This should get the Jenkins builds running for python 3.7 and 3.8.

## Changes proposed in this PR:
- Add additional arguments (for SSL cert chains) to '`pyomo download-extenstions`' in `.jenkins.sh`
- Add a `--verbose` option to `download-extensions` for diagnosing download failures
- Fix an (unrelated to downloading) syntax error that Python 3.8 points out

### Legal Acknowledgement

By contributing to this software project, I agree to the following terms and conditions for my contribution:

1. I agree my contributions are submitted under the BSD license.
2. I represent I am authorized to make the contributions and grant the license. If my employer has rights to intellectual property that includes these contributions, I represent that I have received permission to make contributions and grant the required license on behalf of that employer.

### CODE REVIEW

**Comment by qtothec** [comment]
Do we ever document how `download-extensions` works anywhere?

**Comment by blnicho** [comment]
@qtothec, no I don't think `download-extensions` is really documented anywhere. The rst file for the MC++ shows the syntax for using it but I wouldn't count that as formal documentation.

**Comment by blnicho** [comment]
@jsiirola is this ready to merge now?

**Comment by jsiirola** [comment]
@blnicho: yes.

**Pull request merged**
