### PR TITLE
[WIP] Try out Github Actions

### PR DESCRIPTION
**Pull request by qtothec**
# Summary/Motivation:
Trying out Github Actions

### Legal Acknowledgement

By contributing to this software project, I agree to the following terms and conditions for my contribution:

1. I agree my contributions are submitted under the BSD license.
2. I represent I am authorized to make the contributions and grant the license. If my employer has rights to intellectual property that includes these contributions, I represent that I have received permission to make contributions and grant the required license on behalf of that employer.

### CODE REVIEW

**Comment by qtothec** [comment]
I am not setting up the testing execution correctly somehow, but this seems rather promising.

**Comment by carldlaird** [comment]
@qtothec This looks interesting. Is this WIP right now?

**Comment by qtothec** [comment]
@carldlaird Yes, but I'll probably need some help getting it operational. Plus we ought to have a discussion around how it would fit into the overall testing infrastructure.

**Comment by blnicho** [comment]
It looks like this is revealing an issue in some of the trust region tests, they seem to implicitly require Ipopt.

**Comment by blnicho** [comment]
@mrmundt @allevin @qtothec it passed!

**Comment by mrmundt** [comment]
@blnicho @qtothec @allevin  - I KNOW! I might have been impatiently waiting for your PR to be merged. Thank you!

**Comment by blnicho** [comment]
It was surprisingly fast too, 2.5 minutes to run 6962 tests (1581 skipped).

**Comment by allevin** [comment]
Next steps are to try it on other machines (Mac & WIn), then bump up to matrix builds across python versions.

**Comment by blnicho** [comment]
Ok, I'm really impressed now. Only 3.5 minutes to complete "slim" test suites on Python 2.7, 3.5, 3.6, and 3.7 on Linux

**Comment by mrmundt** [comment]
Impressively quick. It's amazing. I'm about to start a run for MacOS with just Python 2.7. Let's see if the trend of success continues!

**Comment by qtothec** [comment]
This is separate from getting this to work, but is there a way to manage the console output so that you don't have to scroll past pages of successful tests to get to the errors?

**Comment by blnicho** [comment]
There is a lower verbosity level for nosetests but I think in most cases we would want to be able to see exactly which tests were run instead of ". . . . . . S . . . F"

**Comment by allevin** [comment]
I think we can take the -v off the test run to reduce the output to just the errors...

**Comment by mrmundt** [comment]
@jsiirola has pointed us to the fact that there is an old editor on macOS's named "pico" - which is triggering the pico tests to start, and thus, all fail. We'll need to address this somehow.

**Comment by qtothec** [comment]
Replacing this with separate PRs for different distributions.

**Pull request closed without merging**
