### PR TITLE
Tracking changes for #65

### LINKED ISSUE #65: Issue cloning an unpickled model that was solved before it was pickled
The following simple example results in a very strange error inside of __setstate__ on the ModelSolutions object:

```python
import pickle
from pyomo.environ import *

m = ConcreteModel()
m.x = Var()
m.o = Objective(expr=m.x)
m.c = Constraint(expr=m.x >= 1)

#                    
# SOLVE A MODEL
#
glpk = SolverFactory("glpk")
glpk.solve(m)

#
# PICKLE THE SOLVED MODEL
#
m_unpickled = pickle.loads(pickle.dumps(m))

#
# CLONE THE UNPICKLED MODEL
#
m_cloned = m_unpickled.clone() # ERROR
```

The exact order here is important: The unpickled version of a model THAT WAS SOLVED BEFORE IT WAS PICKLED can not be cloned. Here is a partial stack trace:
```python
  File "~/Frameworks/Python.framework/Versions/2.7/lib/python2.7/copy.py", line 182, in deepcopy
    rv = reductor(2)
  File "~/Pyomo/pyomo/pyomo/core/base/PyomoModel.py", line 159, in __getstate__
    tmp[name].update( (ComponentUID(obj()), entry) for (obj, entry) in itervalues(data) )
  File "~/Pyomo/pyomo/pyomo/core/base/PyomoModel.py", line 159, in <genexpr>
    tmp[name].update( (ComponentUID(obj()), entry) for (obj, entry) in itervalues(data) )
TypeError: 'NoneType' object is not callable
```
I will expand the pickle tests to expose this.

@whart222, @jsiirola: Mind taking a look?

### PR DESCRIPTION
**Pull request by ghackebeil**
Merging this PR will resolve #65 automatically, so make any fixes for this issue within this PR branch. This initial commit updates the pickle tests in pyomo/solvers/tests/pickling to expose the problem discussed in #65.

### CODE REVIEW

**Comment by whart222** [comment]
@ghackebeil Why are the tests passing for this PR?  I thought they were intentionally failing?

**Comment by ghackebeil** [comment]
The tests require a solver.

I think if were to update this branch against master the failures would pop up (since the travis script on master now installs GLPK).

I'll go ahead and do that now.

**Comment by jsiirola** [comment]
OK - I think I have this fixed and ready to go.  Merging this will #65 and #127.  @ghackebeil, @whart222: can either of you take a look and merge if you agree?

**Comment by jsiirola** [comment]
We discussed this PR at the developers meeting and agreed it was fine conditioned on fixing a test file that had been moved and redesigned (46fe187)

**Pull request merged**
