### PR TITLE
Add solver GCG

### PR DESCRIPTION
**Pull request by jurgen-lentz**
## Fixes 
None, new interface.

## Summary/Motivation:
This PR adds [GCG](https://gcg.or.rwth-aachen.de) support to Pyomo.

## Changes proposed in this PR:
-
-

### Legal Acknowledgement

By contributing to this software project, I have read the [contribution guide](https://pyomo.readthedocs.io/en/stable/contribution_guide.html) and agree to the following terms and conditions for my contribution:

1. I agree my contributions are submitted under the BSD license.
2. I represent I am authorized to make the contributions and grant the license. If my employer has rights to intellectual property that includes these contributions, I represent that I have received permission to make contributions and grant the required license on behalf of that employer.

### CODE REVIEW

**Comment by mrmundt** [comment]
Hi @jurgen-lentz - I see that this is a draft PR; however, I have a question. What does this achieve that using `asl:gcg` does not? From `pyomo help --solvers`:

```
Pyomo also supports solver interfaces that are wrappers around third-
party solver interfaces. These interfaces require a subsolver
specification that indicates the solver being executed.  For example,
the following indicates that the ipopt solver will be used:

   asl:ipopt

The asl interface provides a generic wrapper for all solvers that use
the AMPL Solver Library.
```

**Comment by mrmundt** [comment]
In theory, yes. I suggest trying it. That being said, fair warning: it will look for the first executable to match `gcg` on the path, so make sure the ASL `gcg` executable is first on the path.

**Comment by jurgen-lentz** [comment]
Yes, it did work indeed. Why has the solver ```scip``` some extra code in Pyomo? ```gcg``` builds on top of ```scip```. Therefore, we thought doing the same would be a good choice (and it is not that much work).

**Comment by mrmundt** [comment]
Honestly, @jurgen-lentz , I am not even sure. That's a choice that far predates me joining the team. We are actively working on refactoring the solver interface system to make it (1) more logical and (2) easier to add to/maintain, and this is one of those cases where we hope to remove complexity. However, I am glad to hear that `gcg` works! I'm closing this PR, but please feel free to contribute in the future.

**Pull request closed without merging**
