### PR TITLE
Logical Expression System - v1

### LINKED ISSUE #414: Define a location for logical functions
We've started using Expr_if() to define a logical IF clause.  But there are other logical functions that we should consider supporting:  ThereExists(), ForAll(), etc.

I think we should put these in a well-named package that provides scoping for these functions.  For example, the following might make sense:
```
from pyomo.environ import *

expr = logical.IF( ... )
```

### LINKED ISSUE #1290: [PEP] Logical Expression System
## Proposal
This PEP proposes extending Pyomo modeling capability to explicitly support Boolean logic—implications, equivalences, etc. It comes in two parts:
1. A long-term vision for supporting the interplay of logical and algebraic modeling constructs (e.g. relational expressions x + y \leq 1)
2. A backwards-compatible bridge implementation (work-in-progress at #1115)

## Motivation
A key part of Generalized Disjunctive Programming theory is the ability to specify logical propositions, such as Y_1 \Rightarrow Y_2. This functionality is currently missing from Pyomo. In addition, there is interest in support for constraint programming solvers, which would benefit from a logical expression system.

## Discussion

- [ ] TODO talk about all the new classes and implementation nuances here
- [ ] TODO talk about the open questions

### PR DESCRIPTION
**Pull request by Justinyl**
Fixes #1290 Fixes #414

## Summary/Motivation:
This is the work in progress pull request for the logical expression system. Mainly here to see how changes will affect core code for now as we refine this to integrate neatly with the numeric 

### Legal Acknowledgement

By contributing to this software project, I agree to the following terms and conditions for my contribution:

1. I agree my contributions are submitted under the BSD license.
2. I represent I am authorized to make the contributions and grant the license. If my employer has rights to intellectual property that includes these contributions, I represent that I have received permission to make contributions and grant the required license on behalf of that employer.

### CODE REVIEW

**Comment by qtothec** [comment]
Open question @jsiirola: should we support use of `__and__` and `__or__` to generate LogicalExpression objects?

**Comment by jsiirola** [comment]
@qtothec: yes, I think so.  Just remember `__and__` and `__or__` are binary and and or (that is, `&` and `|`, not `and` and `or`).

**Comment by qtothec** [comment]
At this point, I consider this iteration more or less feature-complete.

Remaining tasks include:
- [ ] verifying correct precedence for operations
- [ ] verifying correctness by improving test coverage

**Comment by carldlaird** [comment]
@qtothec @Justinyl Can this be closed - i.e., is it superseded by other PRs?

**Comment by qtothec** [comment]
@carldlaird Yes. All of Justin's commits form the foundation of the other PR, so they would make it in pending that merge.

**Pull request closed without merging**
