### PR TITLE
[WIP] Nested decomp

### PR DESCRIPTION
**Pull request by cristianallara**
## Changes proposed in this PR:
-
-

### Legal Acknowledgement

By contributing to this software project, I agree to the following terms and conditions for my contribution:

1. I agree my contributions are submitted under the BSD license.
2. I represent I am authorized to make the contributions and grant the license. If my employer has rights to intellectual property that includes these contributions, I represent that I have received permission to make contributions and grant the required license on behalf of that employer.

### CODE REVIEW

**Comment by whart222** [comment]
@jsiirola I seem to recall discussing with you that this example would sit better as a contrib package.  Do you recall?

**Comment by carldlaird** [comment]
Not sure if you discussed this with John or not, but I agree. I asked for this to be moved from core Pyomo to examples, however, this was before contrib really existed. I think we should add an examples directory to contrib, and put this there.

We have asked Cristiana to move this already (and she did), so let's make sure we know where we want it before asking again (or move it ourselves).

**Comment by whart222** [comment]
Do we really want a pyomo.contrib.examples sub-package?  I hadn't thought of that, and I'm inclined to use a simpler directory structure.

**Comment by mrmundt** [comment]
This has been added to the [Archived design discussions wiki](https://github.com/Pyomo/pyomo/wiki/Archived-Design-Discussions); will close for now.

**Pull request closed without merging**
