### PR TITLE
Sphinx Documentation for Pyomo Network

### LINKED ISSUE #297: Design documentation for connectors
Connectors are poorly documented right now, but they are a key capability for ongoing projects like IDAES.  I think we need to have design documentation for this capability to help us evaluate ongoing development and PRs.

### PR DESCRIPTION
**Pull request by gseastream**
## Summary/Motivation:
Add a thorough reference for everything the pyomo network package provides.

To those reviewing, I would definitely appreciate more ideas on what else could be documented or if there could be more examples of functionality. However, I think I am of the opinion that (depending on the types of things people want to see added), we can merge this and save major additions for a future PR. That way we can at least get this much documentation up there.

## Changes proposed in this PR:
- Add sphinx docs page for Pyomo Network to the modeling extensions section

### Legal Acknowledgement

By contributing to this software project, I agree to the following terms and conditions for my contribution:

1. I agree my contributions are submitted under the BSD license.
2. I represent I am authorized to make the contributions and grant the license. If my employer has rights to intellectual property that includes these contributions, I represent that I have received permission to make contributions and grant the required license on behalf of that employer.

### CODE REVIEW

**Comment by gseastream** [comment]
And yes, this did come a lot earlier than expected. But as the saying goes, when life gives you an 8 hour delay...

**Comment by qtothec** [comment]
You seem to have some doctest failures in one of the travis runs:
<details>
<summary>Test log</summary>
```text
Document: modeling_extensions/network
-------------------------------------
**********************************************************************
File "modeling_extensions/network.rst", line 315, in default
Failed example:
    seq = SequentialDecomposition(tol=1.0E-3) # options can go to init
Exception raised:
    Traceback (most recent call last):
      File "/usr/local/lib/python3.6/doctest.py", line 1330, in __run
        compileflags, 1), test.globs)
      File "<doctest default[16]>", line 1, in <module>
        seq = SequentialDecomposition(tol=1.0E-3) # options can go to init
      File "/home/travis/build/Pyomo/pyomo/pyomo/network/decomposition.py", line 152, in __init__
        raise ImportError("This class requires numpy and networkx")
    ImportError: This class requires numpy and networkx
**********************************************************************
File "modeling_extensions/network.rst", line 316, in default
Failed example:
    seq.options.select_tear_method = "heuristic" # or set them like so
Exception raised:
    Traceback (most recent call last):
      File "/usr/local/lib/python3.6/doctest.py", line 1330, in __run
        compileflags, 1), test.globs)
      File "<doctest default[17]>", line 1, in <module>
        seq.options.select_tear_method = "heuristic" # or set them like so
    NameError: name 'seq' is not defined
**********************************************************************
File "modeling_extensions/network.rst", line 323, in default
Failed example:
    seq.run(m, initialize)
Exception raised:
    Traceback (most recent call last):
      File "/usr/local/lib/python3.6/doctest.py", line 1330, in __run
        compileflags, 1), test.globs)
      File "<doctest default[19]>", line 1, in <module>
        seq.run(m, initialize)
    NameError: name 'seq' is not defined
**********************************************************************
```

</details>

**Comment by gseastream** [comment]
Pro tip: if you want to put code blocks in the collapsed details section, you need newlines between the triple quote thing and the html tags.

**Comment by gseastream** [comment]
How do you skip tests in the doc tests? It's failing on the build that doesn't install numpy or networkx.

**Comment by qtothec** [comment]
You might need to hack something together for conditional skip: https://github.com/sphinx-doc/sphinx/issues/5273

**Comment by gseastream** [comment]
@qtothec it looks like someone is working on implementing conditional skips for doctests, but I have no idea what the turnaround time on that will be. For now I just switched to what I think is an untested version, a code block.

**Comment by DLWoodruff** [comment]
Looks good to me.

**Pull request merged**
