### PR TITLE
Gams writer fix for expr_dev

### PR DESCRIPTION
**Pull request by qtothec**
## Summary/Motivation:
The GAMS `power(x, y)` function is intended only for integer `y` exponent values. This change uses the GAMS `x ** y` operator for real number `y` exponents. 

### Legal Acknowledgement

By contributing to this software project, I agree to the following terms and conditions for my contribution:

1. I agree my contributions are submitted under the BSD license.
2. I represent I am authorized to make the contributions and grant the license. If my employer has rights to intellectual property that includes these contributions, I represent that I have received permission to make contributions and grant the required license on behalf of that employer.

### CODE REVIEW

**Comment by whart222** [comment]
@qtothec Please (1) add a test to confirm the desired behavior, and (2) add a note to the CHANGELOG about this PR.  Thx

**Comment by jsiirola** [comment]
CHANGELOG is not necessary/appropriate, as this is fixing an error on expr_dev and not changing behavior from a previous release.

**Comment by whart222** [comment]
If we're starting to see PRs applied to branches, then I think it's reasonable to document them in the CHANGELOG.

**Comment by blnicho** [comment]
Why not just use '**' always (even in the case of integer exponents)?

**Comment by whart222** [comment]
@qtothec I don't understand your comment about the 'string'.  Internally, none of the elements of an expression tree are strings.

**Comment by qtothec** [comment]
@blnicho There's an advantage to using `power()` for integer exponents, because GAMS has slightly specialized behavior for it. Specifically, `0 ** 3` yields an error but `power(0, 3)` does not. `x ** y` results in `exp(y * log(x))`.

@whart222 I was trying to interrogate the type of `tmp[1]` in the changed code, and it appeared to be `str`.

**Comment by whart222** [comment]
@qtothec Note that `tmp` is defined at the beginning of this function, and that it's a function of the values of the node arguments (see line 53).  So you can query the value of `node._args_[1]`  (or, better yet, `node.arg(1)`).

**Comment by qtothec** [comment]
Thanks. That makes a lot more sense. Aside from baseline test change failures, I hope this should work now.

**Comment by whart222** [comment]
I'm closing this, after migrating these changes to PR #449

**Comment by whart222** [comment]
@qtothec Do you need help with these test failures?  I'm not sure I understand your intent.

**Comment by qtothec** [comment]
I'm hoping that my most recent commit on #454 resolved the failures.

**Pull request closed without merging**
