### PR TITLE
contrib.piecewise: Adding nonlinear-to-piecewise-linear transformation

### PR DESCRIPTION
**Pull request by emma58**
## Summary/Motivation:

This PR adds a transformation that takes a MINLP model and automatically generated a piecewise-linear approximation of the model that can then be transformed to MILP using the other transformations in contrib.piecewise.

## Changes proposed in this PR:
- Adds `contrib.piecewise.nonlinear_to_pwl` transformation
- Adds a lot of tests
- Sneaks in a fix to correctly handle LogicalConstraints in the transformations from piecewise linear to GDP/MIP

### Legal Acknowledgement

By contributing to this software project, I have read the [contribution guide](https://pyomo.readthedocs.io/en/stable/contribution_guide.html) and agree to the following terms and conditions for my contribution:

1. I agree my contributions are submitted under the BSD license.
2. I represent I am authorized to make the contributions and grant the license. If my employer has rights to intellectual property that includes these contributions, I represent that I have received permission to make contributions and grant the required license on behalf of that employer.

### CODE REVIEW

**Comment by emma58** [comment]
This is actually ready for review when folks have a chance--the only remaining failure is the weird seg fault that keeps happening in win/3.11.

**Comment by emma58** [comment]
Oops, I think this is failing coverage because we don't have `lineartree` installed anywhere for testing...

**Comment by emma58** [comment]
If this passes tests, it is ready for review!

**Comment by emma58** [comment]
@mrmundt @jsiirola Are the pypy failures my fault? They seem consistent.

**Comment by jsiirola** [comment]
> @mrmundt @jsiirola Are the pypy failures my fault? They seem consistent.

Yes - I think so.  Because you added `linear-tree`, that triggered pip to install `scipy`, which is known to have issues under pypy (which is why we exclude it).

I think the resolution is to add `linear-tree` to `PYPY_EXCLUDE: scipy numdifftools seaborn statsmodels` in `.github/workflows/test_pr_and_main.yml` and `.github/workflows/test_branches.yml`.  Note that you need to update `.github/workflows/test_branches.yml` to add `linear-tree` to PYPI_ONLY , too...

**Comment by emma58** [comment]
Oooof, now I broke everything?

**Comment by blnicho** [comment]
@emma58 GitHub was having issues yesterday so I just kicked off the GHA tests again to see if that fixes things.

**Review by jsiirola — CHANGES_REQUESTED** [review]
Overall, this looks pretty good.  One thing that should be changed, though (defer the construction of the visitor, or move it to an instance attribute)

**Review by jsiirola — APPROVED** [review]

**Pull request merged**
