### PR TITLE
Update data in Parmest example to match paper results

### PR DESCRIPTION
**Pull request by adowling2**
## Fixes:
- The Rooney & Biegler (2001) example in Parmest had a mistake in the data. With this fix, the estimated results now match the pushed paper.

## Summary/Motivation:
- This is a precursor to testing the covariance estimation feature ;)

## Changes proposed in this PR:
- Updated a single data file.
- Added a more complete reference for the data set (specific table number in a textbook).

### Legal Acknowledgement

By contributing to this software project, I have read the [contribution guide](https://pyomo.readthedocs.io/en/stable/contribution_guide.html) and agree to the following terms and conditions for my contribution:

1. I agree my contributions are submitted under the BSD license.
2. I represent I am authorized to make the contributions and grant the license. If my employer has rights to intellectual property that includes these contributions, I represent that I have received permission to make contributions and grant the required license on behalf of that employer.

### CODE REVIEW

**Comment by jsiirola** [comment]
@adowling2, is this example not tested, or does the test just not verify the result was correct?

**Comment by adowling2** [comment]
@jsiirola The test result did not match the published result in Rooney & Biegler (2001). There was a slight error when copying the data from Bates & Watts (1988) to the Pyomo example. (Rooney & Biegler just refer to Bates & Watts for the data.) I was trying to get the covariance matrix calculated by Pyomo (separate pull request) to match Rooney & Biegler (2001) and traced down this mistake as part of the issue.

**Comment by jsiirola** [comment]
Right.  My question was just that this PR changes the input data but didn't have to change any tests, which led me to wonder if the example wasn't being tested, or if it was, are the tests not verifying that they are getting the same answer from the paper.

**Comment by adowling2** [comment]
@jsiirola The example is being tested. The data is just redefined in the test script using the  "wrong" data. ("6" instead of "7" for the last time data.)

Right now, the pull request just fixes the data for the user-facing example. I only really found this because I was comparing results against the originally paper and it did not match up.

**Comment by carldlaird** [comment]
@adowling2 I agree with @jsiirola. Can we also update the test if this same data mistake is there?

**Comment by adowling2** [comment]
@carldlaird Yes, I can look into that. @jsiirola also raised a point that the current tests duplicate the examples. A more robust approach is to directly call the examples in the test suite. I can look into this.

**Comment by adowling2** [comment]
I created PR #1484 to overhaul the parmest testing.

**Pull request merged**
