### PR TITLE
Update IDAES branch from pyomo/master

### PR DESCRIPTION
**Pull request by jsiirola**
I am recreating @qtothec's PR (#152) now that #151 has been merged with master.

As @qtothec pointed out: IDAES/models will begin to fail tests if the fix to symbolic.py isn't merged in, because of a switch to using the Pyomo differentiate() function rather than going through CasADi.

Attn:
@eslickj
@andrewlee94
@tony121psu
@dangunter

### CODE REVIEW

**Comment by eslickj** [comment]
I'm okay with this.  I think we will have a minor issue with ExternalFunctions related to the AMPLFUNC environment variable, but we need to work that out anyway, and it won't break any tests.  Otherwise I think this works fine for my stuff.

**Comment by andrewlee94** [comment]
My only concern is the same one John has. Otherwise, I would like to update to the new master for the fix to solving indexed blocks.

**Comment by jsiirola** [comment]
I am looking at #153 right now.  @andrewlee94: are you referring to #73?  I will take a look at that next.

**Comment by dangunter** [comment]
I am fine with this if John and Andrew are.

I think @ksbeattie was going to be "gatekeeper", at least initially.

**Comment by andrewlee94** [comment]
@jsiirola The issue we are referring to is the follow on from #73 we mentioned at the meeting. To recap, the AMPLFUNC environment variable does not seem to be getting registered for those people using newer versions of Pyomo.

**Comment by ksbeattie** [comment]
I believe I did agree to be the "gatekeeper" for these PRs.  As in, I was supposed to be the one making the request.  I appear to have fallen down in that regard for this request.

As such, I'm ok with merging this PR as clearly everyone is ok with it.

I'll make a point of driving these requests in the future from the IDAES team.

**Pull request merged**
