### PR TITLE
Fixing logic in NEOS

### PR DESCRIPTION
**Pull request by whart222**
New code for Python 3.x had clear errors.  The name of a function argument changed between the 2.x and 3.x
versions.

## Summary/Motivation:
This PR is a simple fix to an obvious error in new Python 3.x logic in NEOS.

## Changes proposed in this PR:
- Simple changes.

### Legal Acknowledgement

By contributing to this software project, I agree to the following terms and conditions for my contribution:

1. I agree my contributions are submitted under the BSD license.
2. I represent I am authorized to make the contributions and grant the license. If my employer has rights to intellectual property that includes these contributions, I represent that I have received permission to make contributions and grant the required license on behalf of that employer.

### CODE REVIEW

**Comment by whart222** [comment]
@jsiirola This PR suggest that there is a problem with Pyomo's testing.  I thought that NEOS tests were being executed by default (e.g. when running test.pyomo).  And I thought we were testing Pyomo on Python 3.x.  But if so, then it isn't clear why those tests are passing, given this obvious bug.

**Comment by jsiirola** [comment]
I don't understand what you are changing here - as indicated in the code comments, both `ProxiedTransport` classes were derived nearly verbatim from the respective Python 2 / 3 documentation (and the documentation changes the name of the argument between 2 and 3).  Regardless, that change has no impact (that I can find) on how our code runs.

The NEOS proxy interface is tested via Jenkins on all versions of Python.  I just looked, and it is running correctly and passing tests.

**Comment by whart222** [comment]
On a new machine, this code failed on line 89, because the variable 'proxy' was not defined.

**Comment by blnicho** [comment]
Is this related at all to #1201?

**Comment by blnicho** [comment]
@jsiirola I think this is fixing a copy/paste error introduced in https://github.com/Pyomo/pyomo/commit/b4b1368a46f536ceb8bf5c0a890faf8a9f91b3ad. Maybe the better fix would be changing `proxy` to `host` on line 89?

```
        def set_proxy(self, host):
            self.proxy = urlparse(host)
            if not self.proxy.hostname:
                # User omitted scheme from the proxy; assume http
                self.proxy = urlparse('http://'+proxy)  # <-- Line 89
```
This bug wasn't revealed in our tests because line 89 is not covered.

**Comment by jsiirola** [comment]
@blnicho: that makes sense.  I agree that the better fix would be just to change line 89.

**Comment by blnicho** [comment]
@whart222 @jsiirola I made the small change to line 89 discussed above. I have no idea how to test this part of the code though.

**Pull request merged**
