### PR TITLE
Coramin

### PR DESCRIPTION
**Pull request by michaelbynum**
## Summary/Motivation:
This PR moves Coramin from https://github.com/coramin/coramin into pyomo.contrib. Coramin is a library of tools for MINLP-related things (e.g., convex relaxations, domain reduction, etc).

## Still needs done:

- [ ] Update examples
- [ ] Create docs
- [ ] Fix tests
- [ ] Fix imports/dependencies

### Legal Acknowledgement

By contributing to this software project, I have read the [contribution guide](https://pyomo.readthedocs.io/en/stable/contribution_guide.html) and agree to the following terms and conditions for my contribution:

1. I agree my contributions are submitted under the BSD license.
2. I represent I am authorized to make the contributions and grant the license. If my employer has rights to intellectual property that includes these contributions, I represent that I have received permission to make contributions and grant the required license on behalf of that employer.

### CODE REVIEW

**Comment by ZedongPeng** [comment]
Hi @michaelbynum . Is it possible to integrate `Coramin` with `MindtPy`?

**Comment by ZedongPeng** [comment]
Hi @michaelbynum . Is there an estimated timeline for merging the current PR?

**Comment by michaelbynum** [comment]
I am aiming for the end of the month.

**Comment by michaelbynum** [comment]
I think I have a strategy for splitting this into multiple PRs.

**Pull request closed without merging**
