### PR TITLE
Use dict comprehension for constructing dictionaries

### PR DESCRIPTION
**Pull request by blnicho**
## Summary/Motivation:
This PR replaces all the uses of the `dict()` constructor with dict comprehension (where it was straightforward to do so). This PR has minor performance implications as we discovered that dict comprehension is the fastest way to build dictionaries. I'm not sure how to quantify the impact this will have on performance as the minor improvement I saw on my VM was within the error margin for timing Python. 

I'm opening this PR to not lose track of work done during the Pyomo developer sprint and to ask for suggestions on quantifying the performance impact of these changes. 

## Changes proposed in this PR:
- Use dictionary comprehension to construct dictionaries

### Legal Acknowledgement

By contributing to this software project, I agree to the following terms and conditions for my contribution:

1. I agree my contributions are submitted under the BSD license.
2. I represent I am authorized to make the contributions and grant the license. If my employer has rights to intellectual property that includes these contributions, I represent that I have received permission to make contributions and grant the required license on behalf of that employer.

### CODE REVIEW

**Comment by qtothec** [comment]
Close and reopen to re-run everything

**Comment by blnicho** [comment]
@qtothec I'm going to cancel these builds as they will fail until #1245 is merged.

**Comment by qtothec** [comment]
Oh, gotcha. Oops. Looked at this before I got to that one.

**Comment by blnicho** [comment]
At the dev meeting today it was suggested that I try using the standard pyomo test suite (on a quiet machine) to quantify the performance impact of this change.

@jsiirola will also add the dictionary construction timing numbers he was seeing for reference.

I'm going to relabel this as a WIP until we have some of these performance numbers.

**Pull request merged**
