### PR TITLE
Remove Python 2.7, 3.5, and pypy2 from GitHub Actions

### LINKED ISSUE #503: Dropping Support for Python 2.7
This may seem premature, but many major packages in the Python community are planning to drop support for Python 2.7 in or before 2020.  In fact, many major projects are planning to only support bug fixes sometime beforehand:

- http://python3statement.org/

Since we often plan releases in early/mid-fall, I think it's reasonable to plan our last major release supporting Python 2.7 in the fall of 2019.

### LINKED ISSUE #1754: Update manylinux builder once Python 3.9 is added
We use a Marketplace GitHub Action to build our manylinux wheels for release. The main branch of this does not yet have Python 3.9 support, but there is a PR waiting for approval that would add it:

https://github.com/RalfG/python-wheels-manylinux-build/pull/33

Once this PR is merged, we will need to update the release workflow.

### PR DESCRIPTION
**Pull request by mrmundt**
## Summary/Motivation:
We will no longer support anything lower than Python 3.6 starting in Pyomo 6.0.0. This PR is to remove those tests from our GHA suite.

## Changes proposed in this PR:
- Remove `python-2.7`, `python-3.5`, and `pypy2` from push/PR workflows
- Remove `python-2.7` and `python-3.5` from release distribution wheel creation workflow

### Legal Acknowledgement

By contributing to this software project, I have read the [contribution guide](https://pyomo.readthedocs.io/en/stable/contribution_guide.html) and agree to the following terms and conditions for my contribution:

1. I agree my contributions are submitted under the BSD license.
2. I represent I am authorized to make the contributions and grant the license. If my employer has rights to intellectual property that includes these contributions, I represent that I have received permission to make contributions and grant the required license on behalf of that employer.

### CODE REVIEW

**Comment by jsiirola** [comment]
This is great.  Can you also remove 2.7, 3.4, and 3.5 references from:
 - `setup.py`
 - `.coin-or/projDesc.xml`
 - `doc/OnlineDocs/installation.rst`

**Comment by mrmundt** [comment]
> This is great. Can you also remove 2.7, 3.4, and 3.5 references from:
> 
>     * `setup.py`
> 
>     * `.coin-or/projDesc.xml`
> 
>     * `doc/OnlineDocs/installation.rst`

Done!

**Review by michaelbynum — APPROVED** [review]
Does the Jenkins script not need modified?

**Comment by mrmundt** [comment]
> Does the Jenkins script not need modified?

@michaelbynum The Jenkins script doesn't specify (nor care about) the Python version. That's done in the Jenkins job itself.

**Comment by blnicho** [comment]
Would you also remove 2.7, 3.4, and 3.5 references from `README.md`?

**Comment by mrmundt** [comment]
> Would you also remove 2.7, 3.4, and 3.5 references from `README.md`?

@blnicho - That changed was just pushed! Good catch.

**Review by blnicho — APPROVED** [review]

**Comment by blnicho** [comment]
We are waiting to merge this until after the 5.6.3 release

**Comment by mrmundt** [comment]
@jsiirola , @blnicho , @michaelbynum - Anyone want to re-review this?

**Review by blnicho — APPROVED** [review]
I think we can go ahead and merge this

**Comment by michaelbynum** [comment]
I agree.

**Pull request merged**
