### PR TITLE
Add test coverage to linux/osx GitHub actions

### PR DESCRIPTION
**Pull request by mrmundt**
## Summary/Motivation:
The introduction of coverage reports into Github Actions get us one step closer to removing other external dependencies.

## Changes proposed in this PR:
- Add coverage report uploads to Unix workflow

### Legal Acknowledgement

By contributing to this software project, I have read the [contribution guide](https://pyomo.readthedocs.io/en/stable/contribution_guide.html) and agree to the following terms and conditions for my contribution:

1. I agree my contributions are submitted under the BSD license.
2. I represent I am authorized to make the contributions and grant the license. If my employer has rights to intellectual property that includes these contributions, I represent that I have received permission to make contributions and grant the required license on behalf of that employer.

### CODE REVIEW

**Comment by mrmundt** [comment]
The Appveyor build is giving this message:

> Cannot assign job to clouds/groups 'pro, pro-backup'. All clouds within the group are either failing, offline, busy or reached build minutes quota.

The failure isn't related to the PR.

**Comment by jsiirola** [comment]
@mrmundt: we are seeing problems uploading to codecov now:

> ERROR: The coverage upload was rejected because the workflow run is either not in-progress or finished a while ago. Please make sure the workflow run is in-progress and is not stale for uploads to process correctly.

**Comment by mrmundt** [comment]
> @mrmundt: we are seeing problems uploading to codecov now:
> 
> > ERROR: The coverage upload was rejected because the workflow run is either not in-progress or finished a while ago. Please make sure the workflow run is in-progress and is not stale for uploads to process correctly.

And it's failing for OSX now. Sigh. Lovely. I'll see what's up.

**Comment by jsiirola** [comment]
@mrmundt, @blnicho: I think I am done playing with this.  linux/osx are now working and pushing coverage to codecov.  I snuck in a few other changes (mostly renaming things to match the new Travis names).  If you agree, then I think we can merge!

**Comment by mrmundt** [comment]
Looks good to me! Thanks for fiddling with it.

**Pull request merged**
