### PR TITLE
Added coincbc to Windows Github Actions

### PR DESCRIPTION
**Pull request by mrmundt**
## Summary/Motivation:
We want to increase the set of solvers available on Windows through Github Actions.

## Changes proposed in this PR:
- Conda-install coincbc package

### Legal Acknowledgement

By contributing to this software project, I agree to the following terms and conditions for my contribution:

1. I agree my contributions are submitted under the BSD license.
2. I represent I am authorized to make the contributions and grant the license. If my employer has rights to intellectual property that includes these contributions, I represent that I have received permission to make contributions and grant the required license on behalf of that employer.

### CODE REVIEW

**Comment by bernalde** [comment]
As far as I know, the recipe of coincbc does not work for Windows (see https://anaconda.org/conda-forge/coincbc).
On the other hand, you can get the precompiled libraries from AMPL as suggested in this post of the Pyomo forum https://groups.google.com/d/msg/pyomo-forum/w8QUGTpsLMw/-kVrRlODEQAJ

**Comment by mrmundt** [comment]
> As far as I know, the recipe of coincbc does not work for Windows (see https://anaconda.org/conda-forge/coincbc).
> On the other hand, you can get the precompiled libraries from AMPL as suggested in this post of the Pyomo forum https://groups.google.com/d/msg/pyomo-forum/w8QUGTpsLMw/-kVrRlODEQAJ

Looks like you are absolutely correct. @jsiirola - Want me to go about doing it the "download source/extract" route?

**Comment by jsiirola** [comment]
@mrmundt: Sure, let's try the AMPL route.  They have updated the URL for 64-bit binaries to https://ampl.com/dl/open/cbc/cbc-win64.zip.  The other option is to get them from COIN-OR (https://bintray.com/coin-or/download/Cbc).  AMPL lags a little bit behind COIN-OR, but has the benefit of being a static URL.

**Comment by jsiirola** [comment]
Closing this, in favor of using the prebuilt executable from AMPL

**Pull request closed without merging**
