### PR TITLE
Adding a general infrastructure for building extensions

### PR DESCRIPTION
**Pull request by jsiirola**
## Summary/Motivation:
This provides a general approach for extensions (primarily in contrib) to register functions for building compiled extensions, and makes that functionality available through the `pyomo build-extensions` command.

## Changes proposed in this PR:
- refactor `common.fileutils` to add a `Library` singleton and a `find_dir()` method
- adding a utilite for downloading and extracting ZIP archives
- Adding a build harness for `contrib.mcpp` based on distutils

### Legal Acknowledgement

By contributing to this software project, I agree to the following terms and conditions for my contribution:

1. I agree my contributions are submitted under the BSD license.
2. I represent I am authorized to make the contributions and grant the license. If my employer has rights to intellectual property that includes these contributions, I represent that I have received permission to make contributions and grant the required license on behalf of that employer.

### CODE REVIEW

**Comment by qtothec** [comment]
Am I doing something wrong?
```
(pyomo3) qichen@qc-cmu-tower:~/git/pyomo/pyomo/contrib/mcpp$ python setup.py install
Traceback (most recent call last):
  File "setup.py", line 12, in <module>
    from . import build
ImportError: cannot import name 'build'
```

**Comment by jsiirola** [comment]
@qtothec: I just fixed the import in `setup.py`.  However, "setup install" will not do what you want: it will create a Python egg in your site-packages directory that contains the SO, but Pyomo won't be able to find it.  I hooked the build into the distutils system at the recommendation of @michaelbynum because distutils provides a measure of platform independence.

That said, the preferred way to build / install the extensions is through the pyomo command:

    pyomo build-extensions

**Comment by jsiirola** [comment]
This is ready to review.  @blnicho, @carldlaird, @michaelbynum?

**Comment by michaelbynum** [comment]
Just FYI, I am looking at this now.

**Pull request merged**
