### PR TITLE
Fix bug in active variable detection for model size report

### PR DESCRIPTION
**Pull request by qtothec**
## Summary/Motivation:
Fixes logic error due to out-of-scope variable usage not caught earlier because I wrote things in too much of a hurry.

Adds test to exercise detection.

### Legal Acknowledgement

By contributing to this software project, I agree to the following terms and conditions for my contribution:

1. I agree my contributions are submitted under the BSD license.
2. I represent I am authorized to make the contributions and grant the license. If my employer has rights to intellectual property that includes these contributions, I represent that I have received permission to make contributions and grant the required license on behalf of that employer.

### CODE REVIEW

**Comment by qtothec** [comment]
I'm having a hard time figuring out why this PR would cause dataportal failures in Appveypor Python 3.7.

**Comment by jsiirola** [comment]
It looks like this build was picking up a different YAML implementation, causing different but equivalent YAML files to be generated.  I was seeing diffs like:
```
-  index: [1, 2]
+  index:
+     - 1
+     - 2
```
This is likely pointing to a fragility in the YAML comparison.  I am re-running the 3.7 build now to see if it "just goes away", and if it doesn't, then we can dig into why the YAML tests are fragile.

**Comment by qtothec** [comment]
@jsiirola fwiw, I re-ran the test earlier and it gave the same result.

**Comment by jsiirola** [comment]
OK - I just looked:  The 2.7 - 3.6 builds are installing
```
    pyyaml-3.12                |           py36_1         121 KB  conda-forge
```
whereas the 3.7 build is installing
```
    pyyaml-5.1                 |   py37he774522_0         147 KB
```
(note that that is not coming from conda-forge.  I think the short-term solution is to fix the pyyaml version on appveyor to 3.12 until we have a chance to fix the DataPortal tests.  I propose making that chance on this PR.

**Comment by qtothec** [comment]
Are you going to push that change onto this branch? I'm not sure how to go about doing that.

**Comment by jsiirola** [comment]
Sure.  I can do that.

**Comment by jsiirola** [comment]
@qtothec: OK - the build is passing.  Have you verified (by hand?) that the updated baselines are actually correct?

**Comment by qtothec** [comment]
@jsiirola Yes, it makes sense, because none of those models should start with deactivated components.

**Pull request merged**
