### PR TITLE
Deactivate connectors after they have been expanded

### LINKED ISSUE #274: GAMS writer does not accept models with Connector objects
The GAMS writer does not accept models with Connector objects. See discussion in https://github.com/Pyomo/pyomo/pull/253#discussion_r152372039 as well as #310 and #280 and #309

### PR DESCRIPTION
**Pull request by qtothec**
This also required making connectors deactivatable.

Fixes #274.

### CODE REVIEW

**Comment by whart222** [comment]
FWIW, I have a hard time evaluating this PR because we do not have very good documentation on connectors.  Specifically, I'd love to see some design documentation for developers in Sphinx.

**Comment by qtothec** [comment]
Sounds to me like an invitation for a new issue.

**Comment by whart222** [comment]
Good point.  I've added #297 to document the needed for this design documentation.  IMHO, that ticket should be a pre-requisite for completing this PR.

**Comment by jsiirola** [comment]
I do not thing it makes sense to convert Connectors over to ActiveComponents, as it really doesn't make sense to "deactivate" a connector (in the same way that it doesn't make any sense to deactivate a Var or Param.  I recommend closing this PR.

**Pull request closed without merging**
