### PR TITLE
adding install of gurobi to github workflows

### PR DESCRIPTION
**Pull request by michaelbynum**
## Summary/Motivation:
This PR adds installation of gurobi to the github workflows

### Legal Acknowledgement

By contributing to this software project, I have read the [contribution guide](https://pyomo.readthedocs.io/en/stable/contribution_guide.html) and agree to the following terms and conditions for my contribution:

1. I agree my contributions are submitted under the BSD license.
2. I represent I am authorized to make the contributions and grant the license. If my employer has rights to intellectual property that includes these contributions, I represent that I have received permission to make contributions and grant the required license on behalf of that employer.

### CODE REVIEW

**Comment by mrmundt** [comment]
@michaelbynum - I think you may have used tabs instead of spaces (see the big opaque red marks under "Files changed"). GHA can't read tabs, which is why nothing is triggering.

**Comment by michaelbynum** [comment]
@mrmundt Thanks. I have emacs setup so it never uses tabs for py files. I always forget about the issue when working with other file types...

**Review by mrmundt — APPROVED** [review]

**Comment by jsiirola** [comment]
@michaelbynum Does this only apply to the `pip` install?  Do you know if the conda package also includes a limited size license?

**Comment by michaelbynum** [comment]
I think it only applies to the pip install, but I'm not 100% sure.

**Pull request merged**
