### PR TITLE
Remove imports from pyomo.core.expr

### PR DESCRIPTION
**Pull request by whart222**
## Summary/Motivation:
Carl asked whether pyomo.core.expr was dependent on other parts of pyomo.core, which prompted a discussion about the imports used to recognize components.  I realized that I could extend the duck typing in pyomo.core.expr and have an expression system that is completely self-contained!

## Changes proposed in this PR:
- Removing imports from pyomo.core.base and pyomo.repn
- Removed initialization function used in pyomo.environ

### Legal Acknowledgement

By contributing to this software project, I agree to the following terms and conditions for my contribution:

1. I agree my contributions are submitted under the BSD license.
2. I represent I am authorized to make the contributions and grant the license. If my employer has rights to intellectual property that includes these contributions, I represent that I have received permission to make contributions and grant the required license on behalf of that employer.

### CODE REVIEW

**Comment by qtothec** [comment]
Out of curiosity, what did the `standardize` parameter under `expression_to_string` do?

**Comment by whart222** [comment]
The standardize option reorders the terms in a consistent fashion:  constant, linear, quadratic, nonlinear.  If this feature is desirable, we could create a helper function for doing this.  But we decided to not make this the default behavior, so it's not used anywhere by default in Pyomo.

**Comment by whart222** [comment]
I haven't quantified the performance.  I'll add this to our nightly tests.

**Comment by ghackebeil** [comment]
@whart222: Can you go ahead and remove core/tests/unit/test_expr_coopr3.py / test_expr_pyomo4.py on this branch? Every time I run nosetests in that directory I have to remember to temporarily remove those files.

**Comment by whart222** [comment]
@ghackebeil Pulling out the coopr3 and pyomo4 references is not a simple change.  I'll submit another PR for that.

**Comment by whart222** [comment]
The performance change seems either within the normal noise of Python tests or slightly improving, so I'm merging this PR.

**Pull request merged**
