### PR TITLE
Change from %r to %s for NumPy 2.0 compatibility

### LINKED ISSUE #3352: NL file contains np.float64(0.0)
## Summary

I observed pyomo writing `np.float64(0.0)` to the nl file, and I believe it should have been 0.0. I am new to pyomo and am trying to use it with SCIP. When trying to load the model with SCIP, it errors when trying to read the file. Though I can't rule out my error in building the model, I think it is correct. 

I suspect this may be a bug in the nl writer that came from differences in casting `np.float64(0.0)` in numpy 2.0.

### Steps to reproduce the issue

I put some of the relevant bits from my code, but I have not yet been able to generate a minimum example. 

```python
model = model_factory(dist_df, alpha, config) # function contains model = pyo.ConcreteModel()
model.write(filename="test.nl")
```

```console
scip test.nl -AMPL
```

However, I believe the issue is with the old % string formatting in python. It seems `%r` prints out the unwanted text:

```console
'n%s\n' % np.float64(0.0)
'n0.0\n'
'n%r\n' % np.float64(0.0)
'nnp.float64(0.0)\n'
```

This can be seen in https://github.com/Pyomo/pyomo/blob/29f8ede05e668a98fdef44f0554f53868107b716/pyomo/repn/plugins/nl_writer.py#L2025

With the debugger attached, I was able to find the following values:
```console
repn.const
np.float64(0.0)
self.template.const
'n%r\n'
```

Therefore, I think all that is needed is a change to https://github.com/Pyomo/pyomo/blob/29f8ede05e668a98fdef44f0554f53868107b716/pyomo/repn/plugins/nl_writer.py#L2368

### Error Message

Pyomo does not raise any errors. Manually editing the nl file to change `np.float64(0.0)` to `0.0` seems to result in a "solvable problem" ( It says this in the output:`SCIP Status: problem is solved [optimal solution found]`). 

File Excerpt:
```console
root@95c09e6d2975:/app# grep -C10 nnp.float64 untracked/test.nl
n0
C262831
n0
C262832
n0
C262833
n0
C262834
n0
O0 0
nnp.float64(0.0)
x0
r
4 13
1 13
2 8.8
4 1
4 1
4 1
4 1
4 1
```

SCIP Error:
```console
[reader_nl.cpp:1780] ERROR: /tmp/tmpbsv7ds1z.pyomo.nl:117648:2: expected double
[scipshell.c:239] ERROR: Error <-2> in function call
[scipshell.c:305] ERROR: Error <-2> in function call
[scipshell.c:594] ERROR: Error <-2> in function call
```

### Information on your system

Pyomo version: Pyomo 6.7.4a0 (VOTD) - Installed 2024-08-18
Python version: 3.12.4
Operating system: debian bookwork (python:3.12.4-slim-bookworm container)
How Pyomo was installed (PyPI, conda, source): pypi
Solver (if applicable): scip

### PR DESCRIPTION
**Pull request by orthorhombic**
## Summary/Motivation:

This changes %r to %s in the nl_writer for NumPy 2.0 compatibility. I believe this was missed in #3292 

## Changes proposed in this PR:

`const = 'n%r\n'` gets changed to `const = 'n%s\n'`

### Legal Acknowledgement

By contributing to this software project, I have read the [contribution guide](https://pyomo.readthedocs.io/en/stable/contribution_guide.html) and agree to the following terms and conditions for my contribution:

1. I agree my contributions are submitted under the BSD license.
2. I represent I am authorized to make the contributions and grant the license. If my employer has rights to intellectual property that includes these contributions, I represent that I have received permission to make contributions and grant the required license on behalf of that employer.

### CODE REVIEW

**Comment by orthorhombic** [comment]
@mrmundt & @jsiirola  - Just figured I'd tag you here for awareness based on your work with #3292

**Comment by mrmundt** [comment]
Thanks, @orthorhombic ! Could you do me a favor and add a small test that ensures the right behavior is happening? Tests for the NL writer can be found in: https://github.com/Pyomo/pyomo/tree/main/pyomo/repn/tests/ampl <- most likely the `test_nlv2.py` file would be the best bet, but do what feels right.

If you need help, let us know.

**Comment by jsiirola** [comment]
@orthorhombic:  Thank you for catching & resolving this!  This is an important catch / fix ... I took the liberty of resolving a merge conflict and adding a test so that we can get this reviewed and merged for the next release (tomorrow!!).

**Review by jsiirola — APPROVED** [review]
Approved, pending successful tests.

**Review by blnicho — APPROVED** [review]

**Review by mrmundt — APPROVED** [review]

**Comment by orthorhombic** [comment]
Sorry I'm just catching up on messages here. Thanks for the quick turnaround, and glad this could make it into the next release!

If anything comes up, I can take a look a bit later.

**Pull request merged**
