### PR TITLE
Bug fix in interior point/MUMPS memory reallocation logic

### PR DESCRIPTION
**Pull request by Robbybp**
## Fixes 
Fixes a bug in the Interior Point/MUMPS memory reallocation logic, where `_prev_allocation` was not being updated correctly after a symbolic factorization. This was only a problem because symbolic factorization is being performed for every numeric factorization attempt, and would only become apparent if multiple reallocations were necessary.

## Changes proposed in this PR:
- Fix bug by updating `_prev_allocation` to be the max of ICNTL(23) and INFOG(16) after symbolic factorization
- Cast `_prev_allocation` as an int to accurately represent the info sent to MUMPS in ICNTL(23).
- Test to catch the erroneous behavior.

The test to catch this bug is very slow, about 3s. This is because the bug only became a problem if 2 or more reallocation iterations were necessary, so I needed to find an NLP for which this was the case. This is complicated by the fact that memory allocations via ICNTL(23) are rounded to the nearest MB, so I needed a KKT matrix whose actual memory requirement was at least 2 MB greater than the prediction. The NLP in the test file is the smallest/fastest I could find with this property.

I could switch to a test that only requires one iteration of reallocation, which could be made much faster, but would not cover the specific bug I encountered. Also up for debate whether this is more of a "MUMPS test" or an "Interior Point test." It's located in the latter's directory because that's how I encountered it. Suggestions appreciated on both of these counts, or on a smaller KKT matrix that requires 2 MB of reallocation.  

### Legal Acknowledgement

By contributing to this software project, I have read the [contribution guide](https://pyomo.readthedocs.io/en/stable/contribution_guide.html) and agree to the following terms and conditions for my contribution:

1. I agree my contributions are submitted under the BSD license.
2. I represent I am authorized to make the contributions and grant the license. If my employer has rights to intellectual property that includes these contributions, I represent that I have received permission to make contributions and grant the required license on behalf of that employer.

### CODE REVIEW

**Comment by jsiirola** [comment]
Note that this has a failing test under pypy on Travis:
```
======================================================================
FAIL: test_mumps (pyomo.contrib.interior_point.tests.test_realloc.TestReallocation)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/build/Pyomo/pyomo/pyomo/contrib/interior_point/tests/test_realloc.py", line 66, in test_mumps
    self.assertEqual(predicted, 12)
AssertionError: 11 != 12
```

**Comment by Robbybp** [comment]
Noticed. I suspect this is due to a different version of Mumps/PyMumps being used, and will have to either modify my test or add a check for the expected version of Mumps.

**Comment by blnicho** [comment]
Note: This PR will have conflicts with #1505 so we'll have to be careful with the merge

**Comment by Robbybp** [comment]
> Note: This PR will have conflicts with #1505 so we'll have to be careful with the merge

Let me know if I should merge that branch

**Comment by blnicho** [comment]
@Robbybp yes, #1505 has been merged into master so could you merge master into this PR and resolve the conflicts? You'll probably need to update some of your imports.

**Pull request merged**
