### PR TITLE
Rewrite of the Connector component

### LINKED ISSUE #14: display() and pprint() not working on SimpleConnector
I realize that a rewrite of the Connector object implementation is in the works. Wanted to bring this issue to your attention as you're doing that.
Error messages:

```
>>> w.units.out_mix.block.out_port.display()
Connector out_port :  Size=1Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/qichen/.solvers/pyomo/src/pyomo/pyomo/core/base/connector.py", line 302, in display
    ', '.join(sorted(self._conval[None].keys()))+"}"+'\n')
TypeError: sequence item 0: expected string, NoneType found
>>> w.units.out_mix.block.out_port.pprint()
  out_port :    Size=1Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/qichen/.solvers/pyomo/src/pyomo/pyomo/core/base/connector.py", line 277, in pprint
    if self._index_set is not None:
AttributeError: 'SimpleConnector' object has no attribute '_index_set'
```

The structure of the connector is as follows:

```
def conc_connector(flow, frac):
    c = Connector()
    c.add(flow, name="F")
    for key in frac._index:
        c.add(frac[key], name="conc_{0}".format(key))
    return c
```

### PR DESCRIPTION
**Pull request by jsiirola**
This PR is a rewrite of the Connector component to bring it in line with the current Pyomo Component model.

There are several other core infrastructure changes that got implemented to support this:
- change in how all expression cloning works to rely almost exclusively on deepcopy.  Besides being simpler, this means we can leverage expression cloning to do some substitutions.
- Consolidation of some default Component methods in an ABC common to both Component and ComponentData
- Overhaul of pprint() to support single and multi-line output for each key

@ghackebeil, @whart222: please review the core changes.

This PR fixes #14, #39, and #40.

### CODE REVIEW

**Comment by whart222** [comment]
I looked through the code and nothing raised any concerns.

However, I'm now seeing lots of test failures on my Mac that look like a deepcopy problem.  For example:

```
======================================================================
ERROR: test_glpk_lp_non_symbolic_labels (pyomo.solvers.tests.pickling.test_pickle.PickleTests_block_LP)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/wehart/home/src/python27/src/pyomo/pyomo/solvers/tests/pickling/test_pickle.py", line 104, in pickle_test
    instance1 = m.clone()
  File "/Users/wehart/home/src/python27/src/pyomo/pyomo/core/base/PyomoModel.py", line 735, in clone
    instance = SimpleBlock.clone(self)
  File "/Users/wehart/home/src/python27/src/pyomo/pyomo/core/base/block.py", line 1034, in clone
    new_block = copy.deepcopy(self, {'__block_scope__': set( (id(self),) )})
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/copy.py", line 174, in deepcopy
    y = copier(memo)
  File "/Users/wehart/home/src/python27/src/pyomo/pyomo/core/base/component.py", line 572, in __deepcopy__
    ans.__setstate__(deepcopy(self.__getstate__(), memo))
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/copy.py", line 163, in deepcopy
    y = copier(x, memo)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/copy.py", line 257, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/copy.py", line 182, in deepcopy
    rv = reductor(2)
  File "/Users/wehart/home/src/python27/src/pyomo/pyomo/core/base/PyomoModel.py", line 159, in __getstate__
    tmp[name].update( (ComponentUID(obj()), entry) for (obj, entry) in itervalues(data) )
  File "/Users/wehart/home/src/python27/src/pyomo/pyomo/core/base/PyomoModel.py", line 159, in <genexpr>
    tmp[name].update( (ComponentUID(obj()), entry) for (obj, entry) in itervalues(data) )
TypeError: 'NoneType' object is not callable
```

These tests arise when testing with GLPK and IPOPT.

**Comment by ghackebeil** [comment]
Those failures are a result of my commit from yesterday (c95b3092e4a3e932082d98b40e1ca89b69cb6365) which expanded the pickle tests to expose the issue in #65. The "pickle tests" I refer to test the ability to do things like solve a model (that has been pickled) before and after it has been solved. It test over all the available solvers because this actually used to matter.

**Comment by whart222** [comment]
Given that we're planning a release, I'm wondering if we could move those
tests into a PR that documents the need.  What do you think?  I don't
expect we'll resolve this issue right away, and I don't think it should
hold up the 5.0 release.

--Bill

On Thu, Nov 10, 2016 at 5:44 PM, Gabriel Hackebeil <notifications@github.com

**Comment by ghackebeil** [comment]
My hope was that you are John might be able to glance at the __setstate__/__getstate__ methods on ModelSolutions and fine some trivial mistake that was causing this. I'll back the new tests out for now, so we can move on with the release.

**Comment by ghackebeil** [comment]
Done.

**Comment by whart222** [comment]
John said that he looked at it and saw where the bug was but couldn't
figure out exactly what would fix it.

On Thu, Nov 10, 2016 at 6:07 PM, Gabriel Hackebeil <notifications@github.com

**Pull request merged**
