### PR TITLE
[WIP] Implementing feasibility pump

### PR DESCRIPTION
**Pull request by RomeoV**
## Summary/Motivation:
As part of the `MindtPy` toolbox, a tool for finding a feasible solution is undoubtedly an important part. This PR implements the `feasibility pump`, used for finding and improving a feasible solution.

This is especially important since I am also implementing the `Level based outer approximation`, which requires an initial feasible solution. The method is heavily inspired by [this paper](https://pdfs.semanticscholar.org/80f8/a6be126cccd80f938387f99bed14d92ea09a.pdf) by Bernal, Vigerske, Trespalacios, and Grossmann.

## Changes proposed in this PR:
- Implement more additional mindtpy cuts
- Add feasiblity pump configuration options
- Modify nlp_solve, mip_solve, iterate and initialization methods for feasibility pump functionality
- Provide `feas_pump` both as standalone solver and as initialization strategy
- Provide somewhat extensive tests

# Dependencies
This PR depends on #983 and should only be merged after.

### Legal Acknowledgement

By contributing to this software project, I agree to the following terms and conditions for my contribution:

1. I agree my contributions are submitted under the BSD license.
2. I represent I am authorized to make the contributions and grant the license. If my employer has rights to intellectual property that includes these contributions, I represent that I have received permission to make contributions and grant the required license on behalf of that employer.

### CODE REVIEW

**Comment by jsiirola** [comment]
@RomeoV: This PR appears to include #983.  Is that correct?

**Comment by RomeoV** [comment]
Yes. I added it to the PR description.

**Comment by qtothec** [comment]
Something is wrong with the master problem after solving a feasibility problem, it looks like.

**Comment by bernalde** [comment]
Hi @RomeoV , some development has happened in MindtPy since this PR was created. Would you mind giving me, @ZedongPeng and @Justinyl writing access to this PR such that we can work on it?
Thanks!

**Comment by qtothec** [comment]
@bernalde There's no need to do so. Just create a new branch off of this.

**Comment by bernalde** [comment]
The feasibility pump is implemented in an upcoming PR and this can be safely closed.

**Pull request closed without merging**
