### PR TITLE
[MONITOR] Restore Python3.7 testing with extras

### PR DESCRIPTION
**Pull request by jsiirola**
## Summary/Motivation:
This reverts #1180 and restores EXTRAS testing with Python 3.7

## Changes proposed in this PR:
- test Python 3.7 with extras

### Legal Acknowledgement

By contributing to this software project, I agree to the following terms and conditions for my contribution:

1. I agree my contributions are submitted under the BSD license.
2. I represent I am authorized to make the contributions and grant the license. If my employer has rights to intellectual property that includes these contributions, I represent that I have received permission to make contributions and grant the required license on behalf of that employer.

### CODE REVIEW

**Comment by qtothec** [comment]
Oh, this is in relation to #1171? Looks like there's still issues.

**Comment by jsiirola** [comment]
@qtothec correct.  This is going to sit here so we can periodically check to see if the appveyor issue has been resolved.

**Comment by blnicho** [comment]
@mrmundt agreed to take a look at this

**Comment by mrmundt** [comment]
@blnicho @qtothec @jsiirola From what I see, there is this section the AppVeyor build:
```
SET ADDITIONAL_CF_PKGS=setuptools pip coverage sphinx_rtd_theme
SET MINICONDA_EXTRAS=""
IF DEFINED USING_MINICONDA (SET MINICONDA_EXTRAS=numpy scipy ipython openpyxl sympy pyodbc pyyaml networkx xlrd pandas matplotlib dill seaborn)
IF DEFINED EXTRAS (SET ADDITIONAL_CF_PKGS=%ADDITIONAL_CF_PKGS% pymysql pyro4 pint pathos %MINICONDA_EXTRAS%)
SET ADDITIONAL_CF_PKGS=%ADDITIONAL_CF_PKGS% glpk ipopt
%CONDAFORGE% %ADDITIONAL_CF_PKGS%
```
If `EXTRAS` is disabled, Miniconda will try to install: `setuptools, pip, coverage, sphinx_rtd_theme, glpk, ipopt`. Otherwise, Miniconda installs those PLUS a large list that includes `numpy, sympy, pandas`, etc. 

@blnicho and I discussed looking at trying to get this resolved by using Github Actions. In looking at our workflow, *surprise*, it's already working for Python 3.7. By default, @allevin and I already included all of the `EXTRAS` python modules. So I am fairly certain that, since the Windows Github Actions are now working, it's already resolved.

**Comment by blnicho** [comment]
@mrmundt thanks for taking a look at this. One other thing we should check is that the number of tests being run (for a particular version of Python) is the same on Appveyor and Github Actions. I tried doing a quick spot check of this and it looked like fewer tests were being run with Github Actions but this might just be because it has been a while since master was merged into that branch.

**Comment by mrmundt** [comment]
@blnicho - I actually just merged the master into [PR #1233 ](https://github.com/Pyomo/pyomo/pull/1233), so we can spot-check that in a bit here.

**Comment by mrmundt** [comment]
@blnicho - Comparing Python 2.7 (with all the extras) between Appveyor and Github Actions, it looks like a difference of 8 tests. Appveyor skips 1337, Github skips 1345.

**Comment by blnicho** [comment]
@mrmundt thanks for adding that data in. Before we completely disable Appveyor in favor of Github Actions we should figure out why the number of tests are so different across platforms and testing engines. 

The test suite should work (in theory) for Python 3.8. I think the issue is that a 3.8 version of Anaconda is not yet available.

**Comment by jsiirola** [comment]
In addition to checking the number of skipped tests, you also need to check the total number of tests.  nosetests is a bit weird where if an entire test suite (class) is skipped, it is reported as a single skipped tests (and not one for every test method in the class).  There are also a set of programmatically-generated test suites, and it is always possible that in the two environments different numbers of tests get generated/registered.

**Comment by blnicho** [comment]
I'm going to go ahead and close this as we now have the Python 3.7 Windows tests "with extras" running on Github Actions. If/when we decide to disable Appveyor tests I'll open a new issue to track it which will include making sure the number of tests between Appveyor and Gihub Actions are consistent (or at least any differences are accounted for).

**Pull request closed without merging**
