### PR TITLE
[WIP] Modify PyROS Master Feasibility Problem Formulation

### PR DESCRIPTION
**Pull request by shermanjasonaf**
## Summary/Motivation:
With the aim of improving the computational performance of PyROS, we change the formulation of the master feasibility problem, used to initialize variables for the original master model, from
image

to
image

in which:
- *x* denotes the model's first stage variables
- *z^k* denotes the second-stage variables corresponding to iteration _k_
- *y^k* denotes the second-stage variables corresponding to iteration _k_
- *q^k* denotes the uncertain parameter realization obtained from iteration _k_ (and _q^0_ is the nominal realization)
- *d_l* denotes the decision rule variables corresponding to the *l*th dimension of the 2nd stage var space
- _s_ denotes slack variables 
- *c* denotes slack variable  scaling coefficients
- _K_ denotes the iteration set
- _Q_ denotes the uncertainty set

In particular, we add slack variables to the master model constraints corresponding to the uncertain parameter realization derived from the previous iteration only (as opposed to all master model constraints).

## Changes proposed in this PR:
- See summary/motivation

### Legal Acknowledgement

By contributing to this software project, I have read the [contribution guide](https://pyomo.readthedocs.io/en/stable/contribution_guide.html) and agree to the following terms and conditions for my contribution:

1. I agree my contributions are submitted under the BSD license.
2. I represent I am authorized to make the contributions and grant the license. If my employer has rights to intellectual property that includes these contributions, I represent that I have received permission to make contributions and grant the required license on behalf of that employer.

### CODE REVIEW

**Comment by jsiirola** [comment]
@shermanjasonaf Is this still a [WIP], or is it ready for review?

**Comment by blnicho** [comment]
@shermanjasonaf I noticed you merged main into this PR a few days ago. Please remove the "[WIP]" in the title if this is ready for review.

As a general rule we tend to not focus any of our PR review resources on WIP PRs unless specifically asked.

**Comment by shermanjasonaf** [comment]
Understood. I wish to make this PR from a different branch on my fork (and, in doing so, remove the [WIP] from the title). Should I close this PR and open a new PR which is ready for review, or is there an appropriate way to change the source branch for this PR?

**Comment by blnicho** [comment]
@shermanjasonaf I don't think there is a way to change the branch after the PR is opened so I'd recommend closing this and opening a new PR when you're ready.

**Pull request closed without merging**
