### PR TITLE
Resolving pyomo5 expected failures

### LINKED ISSUE #455: Resolving pyomo5 expected failures
This issue documents discussions related to the expr_expected_failures branch.

### PR DESCRIPTION
**Pull request by whart222**
## Summary/Motivation:
Resolves outstanding test failures after Pyomo5 expression merge.

## Changes proposed in this PR:
DAE, PYSP and GDP failures will be addressed here.

### Legal Acknowledgement

By contributing to this software project, I agree to the following terms and conditions for my contribution:

1. I agree my contributions are submitted under the BSD license.
2. I represent I am authorized to make the contributions and grant the license. If my employer has rights to intellectual property that includes these contributions, I represent that I have received permission to make contributions and grant the required license on behalf of that employer.

### CODE REVIEW

**Comment by whart222** [comment]
@ghackebeil @blnicho After removing the pyomo5_expected_failures tag, I'm seeing test failures in PySP and DAE.

@jsiirola Let's re-merge GDP stuff here.

**Comment by blnicho** [comment]
@whart222 which DAE tests are you referring to? Looks like everything passed on Travis

**Comment by ghackebeil** [comment]
@whart222: Same question as @blnicho. I can't reproduce any PySP failures on this branch outside of the what is expected from test_ph.py suite (but none of those were flagged as pyomo5 expected failures). What test command are you executing?

**Comment by jsiirola** [comment]
@whart222: OK - I will work on this branch.  Why is this a PR, though?  It is not ready to merge, is it?

**Comment by whart222** [comment]
NOTE:  I'm closing this for now.  We can minimize testing without this PR.  And we can discuss using issue #455

**Pull request closed without merging**
