### PR TITLE
Document PR Process

### LINKED ISSUE #267: Define Pyomo coding standards
Desired/Required  (Decide on these)
New vs Edit

Summary of Coding Standards
- PEP8 compliant
- Core projects have higher LOF:  pyomo.core, pyomo.opt, pyomo.repn, pyomo.common
- Sphinx compliant documentation
  * Module (Required if new of heavily modified)
  * Public Classes (Required if new or heavily modified)
  * Private Classes (Required for "core", otherwise desired)
  * Public functions (Required if new or heavily modified)
  * Private functions (Required for "core", otherwise desired)

### LINKED ISSUE #304: Contribution guide
I think it might help new developers if there were a kind of contribution guide.  Something along the lines of:

* How to structure pull requests
* What coding guidelines to follow (I guess #267 ?) 
* Where to place / write tests

I don't think it needs to be comprehensive, but I think it would really help getting people on board that would go on to contribute regularly.

### PR DESCRIPTION
**Pull request by qtothec**
## Summary/Motivation:
Add documentation of pull request expectations and conventions.

This fixes #304 and fixes #267.

### Legal Acknowledgement

By contributing to this software project, I agree to the following terms and conditions for my contribution:

1. I agree my contributions are submitted under the BSD license.
2. I represent I am authorized to make the contributions and grant the license. If my employer has rights to intellectual property that includes these contributions, I represent that I have received permission to make contributions and grant the required license on behalf of that employer.

### CODE REVIEW

**Comment by jsiirola** [comment]
I think this is good to add.  @blnicho, @carldlaird: a while ago we put together a longer document regarding PR management.  Was that ever added to the Sphinx docs?  Can we do that as part of this PR (and have the CONTRIBUTING.md file link to it?)

**Comment by blnicho** [comment]
@jsiirola no, it never made it into the Sphinx docs. I'll add it.

**Comment by blnicho** [comment]
@jsiirola and @qtothec, I took a first pass at adding a contribution guide to our Sphinx documentation. It can be found here: https://github.com/Pyomo/pyomo/blob/doc_PR_process/doc/OnlineDocs/contribution_guide.rst

@qtothec could you merge the new `doc_PR_process` branch into this PR?

**Comment by qtothec** [comment]
Sure. In case you would ever want to, you are also able to push changes directly to PR branches since most people leave the "allow edits by maintainers" option checked.

**Comment by gseastream** [comment]
@blnicho I'm just gonna note that in all of `pyomo.contrib`, there are only 5 files with `__author__` set (all in preprocessing, all of them by @qtothec), despite this apparently being a rule...

**Comment by qtothec** [comment]
@gseastream tbh, I had no idea about that rule. The `__author__` that exists is an incidental holdover from porting the functions from IDAES.

**Comment by blnicho** [comment]
I copied the `__author__` thing from the notes from one of our developer meetings but I agree that we haven't been strictly enforcing it in `pyomo.contrib`. We can remove this from the guide if others agree.

This fixes #304 and #267.

**Comment by gseastream** [comment]
I don't think I lean either for or against the author thing. It might be good for being able to trace people down, but then what if another person adds to a file that already has an author...

Also @blnicho if you were trying to use the fix keyword in your last comment to close those issues upon merging this, I believe you (or @qtothec) will have to put that in the PR description, each with their own "fix" word in front of it, for that to work :)

**Comment by jsiirola** [comment]
I believe that we generally avoid `__author__` and instead rely on the commit history to document authors and contributions.  The challenge is that `contrib` packages need a *contact* that the development team can reach out to in the case that the contrib package starts failing tests.  One option is to use `__author__` for that.  The alternative is that the contrib package documenta a package contact as part of their (required?) Sphinx documentation.

**Comment by gseastream** [comment]
FWIW I vote for putting it in the documentation. As for requiring documentation, that sounds like an excellent idea for everyone.

**Comment by qtothec** [comment]
Another challenge is that file renames/moves often obscure history, but I don't feel too strongly about it.

**Comment by gseastream** [comment]
@qtothec that's why whenever I move/rename files I try to make a commit with "move" clearly in the commit message that is strictly copying and pasting code with no internal changes. Then it's fairly easy to follow history.

**Comment by whart222** [comment]
This documentation references a "core" pyomo developer, but that is not defined.  This should  be clarified to make clear the authority and responsibility of a pyomo developer.

**Comment by gseastream** [comment]
How about the top 5 contributors by number of commits?

**Comment by qtothec** [comment]
@gseastream Cute. Commit counts are easily inflated and are also a strong function of development style. I tend to generate more commits because I "hit save" more often.

**Comment by blnicho** [comment]
I think a "core" developer should be anyone with write access to the repository. I have updated the contribution guide accordingly and also updated the coding standards around using `__author__`.

**Pull request merged**
